### ISSUE TITLE
Credential Provider is for Read-Only use cases?

### ISSUE THREAD

**Issue by Lutando** [microsoft/artifacts-credprovider#107]
I just have a question about this project.

Can this artifacts credential provider be used to push packages to our internal Azure Dev Ops Artefacts feed.

If not, can you point me in the right direction in how I can achieve this. Limitations are that I cannot use the yaml tasks to push packages, I should be able to do it from a script.

**Comment by satbai** [comment]
This cred provider will help with authenticating to Azure DevOps Artifacts feeds no matter if you're restoring from a feed or pushing to a feed. You need NuGet version 4.8+ or dotnet SDK version 2.1.400+. 

Are you using the Azure DevOps Pipelines or pushing packages on your dev machine? If using pipelines, the NuGet push task (NuGetCommandV2) will use this cred provider automatically if the NuGet version is 4.8 or greater. If on your dev machine, you can use one of these scripts to install the cred provider to a location on your machine where NuGet and dotnet will be able to find it. More in the [readme](https://github.com/microsoft/artifacts-credprovider/blob/master/README.md#setup).

**Comment by Lutando** [comment]
Thank you. Its a combination of dev machines and other build on other platforms. So it needs to be self contained, non-interactive, and cross plat (this is why the task wont suffice in my use case). Your reply implies that the non-interactive / headless mode of pushing from external location to is not possible?

**Comment by satbai** [comment]
The way the basic mode works is that you have to authenticate interactively the first time and after that the creds will be fetched from cache. Unless you're on Windows and you're already signed in, then Windows Integrated Authentication will be used and you may get authenticated non-interactively the first time.

If interactive mode is not possible in your case, you can try using this cred provider the way the Azure Pipelines NuGet task uses it. To do that you manually set a [PAT ](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops)for each Azure Artifacts feed endpoint and use the environment variable VSS_NUGET_EXTERNAL_FEED_ENDPOINTS with json that contains an array of service endpoints, usernames and access tokens to authenticate endpoints in nuget.config. 

Example: VSS_NUGET_EXTERNAL_FEED_ENDPOINTS = '{"endpointCredentials": [{"endpoint":"http://example.index.json", "username":"optional", "password":"PAT"}, {"endpoint":"http://example-2.index.json", "username":"optional-2", "password":"PAT-2"}]}'

If this environment variable is correctly set with feed endpoints and PATs, and the cred provider is correctly installed to the location nuget/dotnet will be able to find it, the authentication should work.

**Comment by Lutando** [comment]
Thanks @satbai I will give this a try tomorrow, but your guidance makes sense to me so I guess we can close this.

**Comment by Lutando** [comment]
This worked 100% thanks for the help.
