### ISSUE TITLE
non-triage situation

### ISSUE THREAD

**Issue by richlander** [microsoft/artifacts-credprovider#110]
> The Credential Provider accepts a set of environment variables. These are the only two that we recommend setting in non-triage situations.

What is a "non-triage situation"?

See: https://github.com/microsoft/artifacts-credprovider#environment-variables

Do you possible mean "non-interactive"?

**Comment by satbai** [comment]
That is a fair question. I have a PR out to edit the readme right now, so I'm just going to go ahead and cut the word out while I'm at it. Thanks for pointing it out!
