### ISSUE TITLE
nuget.exe install prompts for username and password instead of using this cred provider

### ISSUE THREAD

**Issue by AArnott** [microsoft/artifacts-credprovider#117]
I have run https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1 on my machine and 0.1.18.0 of the credential provider is installed. 

Yet when I try to use `nuget install` I just get a username/password prompt:

```
tools\5.0.2\nuget.exe install -source https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json A
Feeds used:
  https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json

Installing package 'A' to 'D:\git\lib.template'.
MSBuild auto-detection: using msbuild version '16.300.19.37701' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Int.Preview\MSBuild\Current\Bin'.
Please provide credentials for: https://devdiv.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json
UserName: Password:
```

**Comment by AArnott** [comment]
This seems to work when using nuget.exe 5.2.0.

**Comment by satbai** [comment]
I couldn't reproduce this either. It looks like nuget wasn't able to find the cred provider plugin for some reason. Could it be possible that none of the three [nuget plugin discovery methods](https://github.com/NuGet/Home/wiki/NuGet-cross-plat-authentication-plugin#plugin-installation-and-discovery) were set when you saw the error?

**Comment by AArnott** [comment]
Maybe. I'm happy to close the issue on that assumption (and since 5.2.0 works).
