### ISSUE TITLE
$profilePath is not resolved correctly in Windows Docker container

### ISSUE THREAD

**Issue by arvdrpoo** [microsoft/artifacts-credprovider#119]
I have been trying to connect to my company's private nuget feed from inside a docker container and struggled to make it work. 
In the end I found that there was an bug in the copying of the extracted files: they were copied to the folder where the script was run from instead of the UserProfile folder. 

Checking the content of `[System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::UserProfile)` in the intermediate container shows that it is empty (while it should be 'C;\Users\ContainerUser').
The base image I used is `mcr.microsoft.com/dotnet/core/sdk:3.0`

#### Workaround:
Changing ` $profilePath=System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::UserProfile)` to ` $profilePath="C:\Users\ContainerUser\"` made it work in my case.

**Comment by shubham90** [comment]
Thanks @arvdrpoo for your suggestion. This looks like an environment/scripting issue rather than a credprovider issue. I am closing this for now.
