### ISSUE TITLE
Continuous prompting for credentials on Linux / VS Code

### ISSUE THREAD

**Issue by bcraun** [microsoft/artifacts-credprovider#124]
I've installed the credential provider using the one-shot script and verified the locations of the tooling as provided in the description. I assume the correct behavior for the credential provider is to prompt once and terminate. When I run `dotnet restore --interactive` in either an Ubuntu terminal or in VS Code terminal it results in a continuous loop of browser authentications with generated tokens (i.e. repeated requests for authentication with different tokens as shown in the screenshot below). The command never completes unless I leave it running and don't respond within 90 seconds. For each cycle of authentication, I do receive an email confirmation from Azure DevOps for each new token.  Any help on this would be appreciated as it's becoming a blocking issue.

OS: Ubuntu 19.04
VS Code: 1.37.1
.NET Core 2.2

![image](https://user-images.githubusercontent.com/641584/63698991-c85c5800-c7d4-11e9-900f-43e3a72dd4d4.png)

**Comment by bcraun** [comment]
Not sure if this is related, but I'm seeing 401 auth failures when using the credential provider within a Bitbucket Pipeline step that uses Docker. `dotnet publish` fails when run as a step in a Dockerfile. The credential provider works when I just build and test the project in the pipeline without Docker. Is this a known issue or am I missing something?

![image](https://user-images.githubusercontent.com/641584/63893067-0ce71f80-c99e-11e9-8283-4120fbb62dcd.png)

**Comment by zarenner** [comment]
The credential provider can provide credentials that are generated a few different ways:
1. Interactively (via a device code prompt (on windows also via a UI)
2. Via environment variables such as [VSS_NUGET_EXTERNAL_FEED_ENDPOINTS](https://github.com/Microsoft/artifacts-credprovider#unattended-build-agents)
3. [windows only] auto-magically via windows integrated authentication
4. Cached, previously generated by one of the above

In Azure Pipelines, we use #&#8203;2: We populate environment variables with a token generated by the build itself. If you're using Bitbucket pipelines, I assume that if it's already working outside a container it likely means you (or someone) has done something similar and likely set `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS`.

To get auth working within a docker container, you'll need to propagate that environment variable into the container.

Let me know if any of that doesn't make sense or doesn't match your setup.

**Comment by bcraun** [comment]
Yes I am using the VSS_NUGET_EXTERNAL_FEED_ENDPOINTS env var that's working in the standalone build so I'm not sure why it's not working. Would `dotnet publish` behave differently that `the `dotnet build` or `dotnet restore`?

![image](https://user-images.githubusercontent.com/641584/63894256-07d79f80-c9a1-11e9-9731-5c4aa9278346.png)

**Comment by zarenner** [comment]
`dotnet publish` implicitly does a build (which implicitly does a restore); it should be identical from an auth perspective.

Are you absolutely sure that the variable is correctly populated in the container? e.g. if you add a `RUN echo $VSS_NUGET_EXTERNAL_FEED_ENDPOINTS`, do you get what you expect?

If not: I'm not familiar with Bitbucket Pipelines - are you the one invoking the container build? Any reason not to use `ARG` with `--build-arg` rather than ENV?

**Comment by zarenner** [comment]
Yes, I believe that using `ENV` in that manner won't work, and that you likely want to make it an `ARG` and run `docker build ... --build-arg VSS_NUGET_EXTERNAL_FEED_ENDPOINTS=$VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` (or the literal value if not set in the host environment)

**Comment by bcraun** [comment]
So

**Comment by bcraun** [comment]
Maybe I've stared at this too long, but not seeing the issue why `docker build` is failing when using the `--build-arg` for the NuGet config

![image](https://user-images.githubusercontent.com/641584/63897705-014e2580-c9ab-11e9-9754-9f19a5dc68e4.png)

**Comment by bcraun** [comment]
Declaring the `ARG` in the Dockerfile and using the following worked:

`docker build -t ${IMAGE} --build-arg VSS_NUGET_EXTERNAL_FEED_ENDPOINTS .`
