### ISSUE TITLE
InstallCredentialProvider.ps1 fails with dotnet sdk 3.0 docker image

### ISSUE THREAD

**Issue by posaninagendra** [microsoft/artifacts-credprovider#126]
I'm trying to install Credential Provider through dockerfile but looks like it is failing for asp.net core sdk 3.0 (mcr.microsoft.com/dotnet/core/sdk:3.0) docker image.

The script InstallCredentialProvider.ps1 is https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1
```
Step 12/23 : RUN pwsh InstallCredentialProvider.ps1
---> Running in 7c6e24ab258f
Fetching release https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest
Using Microsoft.NetCore2.NuGet.CredentialProvider.zip
Creating temp directory for the Credential Provider zip: C:\Windows\TEMP\CredProviderZip

 Directory: C:\Windows\TEMP
Mode LastWriteTime Length Name
---- ------------- ------ ----
d---- 9/5/2019 11:02 AM CredProviderZip
Downloading https://github.com/microsoft/artifacts-credprovider/releases/download/0.1.18/Microsoft.NetCore2.NuGet.CredentialProvider.zip to C:\Windows\TEMP\CredProviderZip\Microsoft.NuGet.CredentialProvider.zip
Extracting zip to the Credential Provider temp directory
Copying Credential Provider to .nuget\plugins
Copy-Item : Cannot find path 'C:\Windows\TEMP\CredProviderZip\plugins\netcore\CredentialProvider.Microsoft' because it does not exist.
At C:\src\InstallCredentialProvider.ps1:128 char:1
+ Copy-Item ([System.IO.Path]::Combine($tempZipLocation, "plugins", $lo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (C:\Windows\TEMP\Cre…lProvider.Microsoft:String) [Copy-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
The command 'cmd /S /C pwsh InstallCredentialProvider.ps1' returned a non-zero code: 1
```

**Comment by satbai** [comment]
Could you try using the .sh script to install instead of the .ps1 script? 

There's also a sample dockerfile now that you can check out: https://github.com/microsoft/artifacts-credprovider/blob/master/samples/dockerfile.sample.txt

**Comment by satbai** [comment]
There seems to be a bug in the script where it's mixing up Microsoft.NetCore2.NuGet.CredentialProvider.zip and Microsoft.NuGet.CredentialProvider.zip

**Comment by satbai** [comment]
I have added some more logging to the script in my branch. Could you please try again with the new script [here ](https://github.com/microsoft/artifacts-credprovider/blob/users/satbai/zipfix/helpers/installcredprovider.ps1)and send me the logs? I can't repro this so I'm suspicious that there is something different about the docker environment that the script isn't taking into account.

**Comment by satbai** [comment]
Please reopen the issue with new verbose logs if you encounter this again. With verbose logging the script should now give more debugging info. Closing for now due to inactivity.
