### ISSUE TITLE
ADAL should enable use of system creds

### ISSUE THREAD

**Issue by onovotny** [microsoft/artifacts-credprovider#127]
ADAL currently uses PromptBehavior.Always:
https://github.com/microsoft/artifacts-credprovider/blob/master/CredentialProvider.Microsoft/CredentialProviders/Vsts/AdalTokenProvider.cs#L85

Instead, it should use PromptBehavior.SelectAccount, which enables the user to select workplace joined/AAD joined accounts and remove the need to enter in a password again.

**Comment by satbai** [comment]
I'm going to close this issue because it looks like it's a duplicate of https://github.com/microsoft/artifacts-credprovider/issues/161
