### ISSUE TITLE
installcredprovider.ps1 should be digitally signed

### ISSUE THREAD

**Issue by adriandiglio** [microsoft/artifacts-credprovider#129]
When I try to run the powershell script, I get the error:
"installcredprovider.ps1 cannot be loaded. The file C:\Program Files\artifacts-credprovider-master\helpers\installcredprovider.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and settingexecution policy, see about_Execution_Policies at blah blah."

Digitally signing the script will also help protect the integrity of the file.

**Comment by shubham90** [comment]
Hi @adriandiglio ,
We do not sign our scripts in this repo and leave the verification of the hash to the consumer. If you have an execution policy set, you can choose to [unblock](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-executionpolicy?view=powershell-6#examples) this file from that check after verifying the hash. 
I have noted your request to digitally sign this file in the future but I do not have an ETA for it now.

**Comment by f2calv** [comment]
FYI to bypass that error, Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force

**Comment by herenhuang** [comment]
If this is blocking anyone, please let us know! We can reopen, otherwise there is a workaround in the comments.
