### ISSUE TITLE
Where is proxy parameters?

### ISSUE THREAD

**Issue by VerdonTrigance** [microsoft/artifacts-credprovider#136]
Guys, seriously! All other companies do this stuff for their own distribution scripts, but Microsoft - never! It's not funny! How to install this cred provider under the proxy that require authentication?!
I mean this script: https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1
PS: I also tried to use System.Net.WebClient but faced with problem at downloading $releaseUrl
`Unable to resolve the Credential Provider zip file from https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest`

**Comment by tkrick** [comment]
filed an internal work item for us to add this capability. we'll take a look.

**Comment by VerdonTrigance** [comment]
Any updates?

**Comment by satbai** [comment]
I have a PR out to add proxy support. I just need to test it behind a proxy to make sure it works as expected.  If you're behind a proxy feel free to check the PR or try the script [here](https://github.com/microsoft/artifacts-credprovider/blob/4ce28570bfc06152dfad23c948a47a02635c73ae/helpers/installcredprovider.ps1).

**Comment by VerdonTrigance** [comment]
> I have a PR out to add proxy support. I just need to test it behind a proxy to make sure it works as expected. If you're behind a proxy feel free to check the PR or try the script [here](https://github.com/microsoft/artifacts-credprovider/blob/4ce28570bfc06152dfad23c948a47a02635c73ae/helpers/installcredprovider.ps1).

Thank you for PR, but I am trying to Chocolatey whenever is possible and avoid Microsoft package and artifact managers.

**Comment by satbai** [comment]
Thanks! Just for anyone looking for answers here, the correct place to set proxy parameters for .NET is the system proxy config.
