### ISSUE TITLE
NUGET_PLUGIN_PATHS seems to have to be an absolute path

### ISSUE THREAD

**Issue by SamMackrill** [microsoft/artifacts-credprovider#138]
We are using NUGET_PLUGIN_PATHS to get at CredentialProvider.Microsoft.exe, seems it has to be an absolute path. Does anyone know how to make this work as a local path? Being absolute causes us build issues on different machines with different roots.

**Comment by tkrick** [comment]
Hey @SamMackrill , the NUGET_PLUGIN_PATHS contract is owned by the [NuGet client](https://github.com/NuGet/Home/issues). Can you raise this with them?  Thanks.

**Comment by SamMackrill** [comment]
Yes, will do. Just thought as people actively use for this plugin it they might know here. Will report back.

**Comment by SamMackrill** [comment]
Seems this is by design
[https://github.com/NuGet/Home/wiki/NuGet-Package-Download-Plugin#plugin-discovery](url)
