### ISSUE TITLE
Error 500 trying access for the first time to Azure Artifacts

### ISSUE THREAD

**Issue by nrfonseca** [microsoft/artifacts-credprovider#140]
Hello.

When developers try to build their code in their machine for the first time, a popup should open to do the login in Azure with AD and this isn't happening. What happens is that in the command line, a message appears saying to access a link with a code to do that login, however, after the login, the build fails with the message:

`
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(114,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/***/_packaging/***/nuget/v3/index.json. [C:\svn\***\***\Build.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(114,5): error :  Response status code does not indicate success: 500 (Internal Server Error). [C:\svn\***\***\Build.sln] `

However, if the developer access via UI to Azure Artifacts page, and run the build again, he will be able to run the build with success.

**Comment by omokoh** [comment]
Hey, 

Please provide more info, if you are still experiencing this issue

Thanks
