### ISSUE TITLE
vscode dev in docker support

### ISSUE THREAD

**Issue by scabana** [microsoft/artifacts-credprovider#142]
We are using: 
- Windows 10
- vscode latest
- vscode dev in container (https://code.visualstudio.com/docs/remote/containers)
- artifacts-credprovider latest
- Azure DevOps nuget feed

When using the dev in docker extension, git credentials are sync inside of the container and it just works. I tried using the artifacts-credprovider, but interactive is required at least once per image. I would like to be able to mount the cred provider's file to the docker container, something like this: ```"-v", "${env:UserProfile}/AppData/Local/MicrosoftCredentialProvider:/root/.local/share/MicrosoftCredentialProvider/"``` but after a ```dotnet restore``` (that fails), the cred-provider file gets deleted from the folder. 

Is there a way to share/sync the secret within a dev docker image without having make it interactive and create new PATs for every repo (possibly multi since we sometimes need to rebuild the image)?

Thanks!

**Comment by shubham90** [comment]
If you want to pass the PAT(secret) in the docker image, may be you can pass it using build-args. Something like [this](https://github.com/microsoft/artifacts-credprovider/issues/63#issuecomment-464314865). You won't need to use interactive  or create PAT everytime. Just create it once and pass it every time from the caller.

**Comment by scabana** [comment]
In that case, the said PAT would have to be in the env before starting vscode. vscode is the one doing the docker build. The goal would be to have something that's seamless, ideally devs would mostly not need to know that there's a PAT, they would not have to manage it manually: which is this tool's responsibility. 

Thanks for your input!

**Comment by shubham90** [comment]
Alternatively, You can store the PAT in some key vault and pull it from there using some script baked into the flow. 
The tool(credprovider) should need some sort of user authentication(PAT in this case) to verify if user has permissions to the feed. The tool's responsibility is to authenticate the user and provide a session token that is used by nuget/dotnet.

**Comment by shubham90** [comment]
Earlier this year, I did some work to integrate credprovider in dotnet docker images. I am not sure if something like that will solve your issue but I pulled the credprovider from cloud and copied the folder to a custom location and then set an environment variable to let nuget/dotnet know about the custom location. https://github.com/dotnet/dotnet-docker/pull/891/files

**Comment by scabana** [comment]
I'm doing kind of the same, but from what I can understand, your link does not setup authentication. It would still need a PAT or --interactive on the restore. 

Took a quick look at the code, [here](https://github.com/microsoft/artifacts-credprovider/blob/a140be2bcc9f6218fcb09d4397a7a5f4cf8f5582/CredentialProvider.Microsoft/Util/SessionTokenCache.cs#L223-L231), it indicates to fallback to unencrypted if it fails. Haven't tried it, but my guess is that ```ProtectedData.Protect``` fails on linux. So, from that, I would say the file is not encrypted on linux. I think that if I did the restore interactive from linux and never do an interactive again from windows, my scenario would work. But this does go agains't protection of data. The real question here is how could we securely share the host's file with the running container. 

I just want to be fully clear here: 
1. This is not blocking, it just makes things harder than they need to be
2. The goal of this bug is to see if we can come to an easy to come solution
3. May highlight another problem: Token creation without a the ability to control the name could become a problem. For example, we have 10s of repositories that could use dev in docker, if a PAT is not shared across those repos and dev in docker is used, 10s of PATs would be created. And this would become unmanageable.

Again, thanks for the brainstorm, much appreciated!

**Comment by TheAifam5** [comment]
You can pretty easy setup the credential provider in DevContainer.

https://stackoverflow.com/a/60005623/8646410

**Comment by scabana** [comment]
I agree it works, will still not share the auth with the windows one. Also, the linux one doesn't seem to be encrypted like the windows one.

**Comment by TheAifam5** [comment]
Even if I bind on in the Linux host, does not want to use my existing one. 

That would be a nice feature to have but I think, it shouldn’t be too problematic since you need do only login once on the DevContainer.
 I think you can reuse that volume on every other container but I didn’t tested that.

**Comment by herenhuang** [comment]
Closing this since there is a workaround in the comments. If there are any concerns here please let us know!

**Comment by ggirard07** [comment]
Not sure the workaround is enough... I would prefer the PAT to stay on the host and to not be exposed as an env variable in the container by `$VSS_NUGET_EXTERNAL_FEED_ENDPOINTS`.

This is what happens for Git authentication, right?
The auth tokens stay only on the host and are not copied over to the container, the Node.JS based credential helper does the forwarding.
