### ISSUE TITLE
support for AzureDevOPs build agent

### ISSUE THREAD

**Issue by 3GDXC** [microsoft/artifacts-credprovider#149]
IMHO it would be good to have this be a global/local dotnet tool install (from public nuget) as this would allow installation on a AzureDevOps build agent (at build time) and/or with in a docker build image using the dotnet tool --install command.

**Comment by krokofant** [comment]
You can use the [NuGet Authenticate task](https://aka.ms/NuGetAuthenticateTask)

**Comment by herenhuang** [comment]
Hey @3GDXC - can you give some more details about your use case please?

**Comment by herenhuang** [comment]
Hey there, closing this issue. Please reopen if you need any other help.
