### ISSUE TITLE
Install script should redownload every time by default

### ISSUE THREAD

**Issue by gundermanc** [microsoft/artifacts-credprovider#160]
Recently, there was some race condition bug in an older version of the credential provider that would lead to a NullReferenceException thrown with the following stack:

```
   at NuGetCredentialProvider.Cancellation.CancellationExtensions.DumpDiagnosticsCore(StringBuilder sb, CancellationTokenSource node, ImmutableList`1 path, String indent)
   at NuGetCredentialProvider.Cancellation.CancellationExtensions.DumpDiagnostics(CancellationTokenSource cts)
   at NuGetCredentialProvider.Cancellation.CancellationExtensions.DumpDiagnostics(CancellationToken token)
   at NuGetCredentialProvider.Program.<Main>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\694\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\694\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at NuGetCredentialProvider.Program.<Main>(String[] args)
```

In terms of impact, we had [random restore failures on our Azure DevOps build machines with no non-zero exit codes or logged output](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3309492).

In investigating this issue, I found that:
- For some reason, the crashing dotnet.exe process seemed to swallow the exception, so no exception, console output, and no exit code were set, making it show up as an Azure Pipelines failure with no output to aid in diagnosis. Compare this to a 1-off console app that throws.. usually there's output like 'Unhandled exception TYPE...'.
- Artifacts credprovider didn't (doesn't?) archive symbols for the affected version on http://symweb and so I couldn't get sources from my dump.
- The bug appears to have been fixed in a later version of the tool, but we never got it because the the Windows install script [installcredprovider.ps1](https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1) caches the credential provider without performing a version check, so it was never updated from the broken version once it's on the machine. This led to an intermittent failure that gave no output and was machine-dependent.
- There's a `-Force` parameter that enforces redownloading the provider every time. I've adopted it [here](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/218390?_a=overview), and it seems to fix the issue, but it seems like something that could happen to other users of this component.

To prevent such issues going foward, I'd like to propose that a version check is added to invalidate the cached provider OR that the provider is re-downloaded every time so the failure is deterministic across machines.

**Comment by shubham90** [comment]
For scenarios where user wants to download the provider every time, 'Force' switch would be useful and it should be an opt in switch. Changing the defaults would be considered a breaking change.

I like the idea of having some other switch(UpdateOnly) which invalidates the cache only if a new/older version is available. This will save some time in the pipeline if no update is available and/or update the provider if something new is available. Users can chose which switch works best for them. I will talk with the team and see what they think about it.

**Comment by gundermanc** [comment]
The argument against a breaking change is a good one but I'd counter that caching by default in a CI build defeats the purpose by letting machine state affect the outcome of the build.

This was a simple mistake to make and it lead to CIs that we can't trust and about 4 days of lost productivity on the team as we built scripts to capture additional diagnostics from the machine.

Updating to a newer provider is unlikely to break a build in a way that wouldn't already happen when adding and removing machines from a build pool (new machines always download the latest version), however, at least outcome would be consistent across all machines in a pool because they would all use a consistent, new version, regardless of when they are added to the pool.

**Comment by AmadeusW** [comment]
Completely agreed with @gundermanc. The build in the CI pipeline must be deterministic. Consistency of outcomes across all CI machines, and ideally dev machines, is paramount to productivity.

**Comment by edgarrs** [comment]
This is a low priority issue and we are looking at other ways to deliver the CredProvider to avoid these kind of issues
