### ISSUE TITLE
Extra password prompts

### ISSUE THREAD

**Issue by clairernovotny** [microsoft/artifacts-credprovider#161]
The current behavior for the AdalTokenProvider is to use `PromptBehavior.Always`. This forces people to enter a password instead of enabling use of Connected to Windows accounts. The better default should be `PromptBehavior.SelectAccount` as that lets people choose an existing AAD account that's part of Windows, including AADJ accounts.

https://github.com/microsoft/artifacts-credprovider/blob/master/CredentialProvider.Microsoft/CredentialProviders/Vsts/AdalTokenProvider.cs#L86

/cc @bgavrilMS from the MSAL team to confirm best practices.

**Comment by bgavrilMS** [comment]
SelectAccounts is the recommended default for both ADAL and MSAL. In MSAL, you don't need to specify one and the library will choose a value for you (currently SelectAccount)

**Comment by omokoh** [comment]
Hi,

It seems there is a resolution for this issues. Please reopen if you are still experiencing this issue.

Thanks
