### ISSUE TITLE
Is the Credential Provider have to use the Windows password?

### ISSUE THREAD

**Issue by trac3me** [microsoft/artifacts-credprovider#164]
Hello there, great product:
I am using CredentialProvider to develop my custom login method，After my research，the Credential Provider seems to require the user's original Windows password.  my question is : Is the Credential Provider have to know the original Windows password, and pass it to the operating system for verification, Otherwise the user cannot log in successfully?

**Comment by jmyersmsft** [comment]
artifacts-credprovider doesn't have anything to do with logging in to the local machine. Its only purpose is to obtain credentials to authenticate to Azure DevOps, specifically for Azure Artifacts package management scenarios. The user logs in to Azure Active Directory either via a web browser, or in some scenarios an encryption certificate managed by the OS. This is all mediated by [ADAL](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries). The credential provider receives a token from AAD at the completion of this process, which it exchanges for a restricted Azure DevOps session token, which it passes back to the caller to use for authentication.

**Comment by jmyersmsft** [comment]
To be clear, it's _likely_ that the user will use the same credentials to log in to AAD as they use to log in to their computer, but artifacts-credprovider has no direct involvement in that

**Comment by trac3me** [comment]
thank you，you mean the credprovider do not have to use the windows password ？

**Comment by trac3me** [comment]
the user need to use Windows password and send to credprovider ，then credprovider pass it to OS，if the password is wrong， OS will not let the user log in.  this mean the credprovider need to pass right password to OS, otherwise it can not log in. right?

**Comment by jmyersmsft** [comment]
I mean the credprovider has no direct relationship with the windows password. It does not present entered credentials to the OS at all. When the user is prompted to log in to Azure Active Directory, any user in the directory with a valid Azure DevOps license can successfully log in and get a token generated, regardless of what user is logged in to the computer. Depending on how the organization's AAD tenant is configured, the user may or may not even enter a password per se (for instance, here at Microsoft I log in to both my computer and AAD with Windows Hello for Business credentials and don't even know my actual Windows password)

I'm not really sure what you're trying to do, but I don't think artifacts-credprovider will help you do it.

**Comment by jmyersmsft** [comment]
The user does have to pass valid AAD credentials to AAD, which are very likely the same as their Windows credentials, but again this is only an indirect relationship and is not required to be related to the current Windows user or any particular Windows user associated with the user's _computer_.

**Comment by trac3me** [comment]
thank you very much， I want use credprovider to make a program which can let user login without the Windows password，can I ？

**Comment by trac3me** [comment]
Hi ， great product:：
    My computer didn't join in Azure AD and Windows Server AD, I just login  local machine. In this scenario, Is the Credential Provider have to use the Windows password?  The user logs in with my credprovider and needs to enter the Windows password, then my credprovider send the passowrd to OS, otherwise it can not log in. Right ? ? 
    I mean the OS need credprovider Provide the original Windows password, right ??

**Comment by jmyersmsft** [comment]
I'm sorry, but artifacts-credprovider is not at all related to what you're looking for.
