### ISSUE TITLE
how do I install the artifact-credprovider in a windows docker image

### ISSUE THREAD

**Issue by jeffpriz** [microsoft/artifacts-credprovider#169]
I am trying to utilize this inside a docker multi-stage build to get the cred provider to read my Azure DevOps NuGet feed.. however the sample docker file doesn't seem to work:
[91m'wget' is not recognized as an internal or external command,
operable program or batch file.
[0mThe command 'cmd /S /C wget -qO- https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh | bash' returned a non-zero code: 255
##[error]C:\Program Files\Docker\docker.exe failed with return code: 255

If I attempt to use the sample found in the dotnet docker here (which uses curl instead of wget):
https://github.com/dotnet/dotnet-docker/blob/master/samples/snippets/nuget-credentials.md#using-the-azure-artifact-credential-provider

I get an error about bash not being a known command.. so.. I'm looking to find a way to utilize this inside my dockerfile successfully.

**Comment by f2calv** [comment]
This is untested, but something like the following should get you there;
```
ADD https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1
RUN powershell .\installcredprovider.ps1 -AddNetfx
```

**Comment by bahman616** [comment]
You can have a look at #148 . Seems like you should be able to use something like this:

`
RUN Invoke-WebRequest 'https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1' -OutFile installcredprovider.ps1;
RUN .\installcredprovider.ps1 -Force 
RUN Remove-Item .\installcredprovider.ps1;
`

**Comment by starx207** [comment]
I was able to get it working using curl and pwsh (I'm using dotnet/core/sdk:3.1 as my base image)

```
RUN curl https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1 | pwsh
```

**Comment by herenhuang** [comment]
Hey @jeffpriz - are you still blocked here?

**Comment by herenhuang** [comment]
Closing this, pls reopen if needed.
