### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream

### ISSUE THREAD

**Issue by mauriciomoccelin** [microsoft/artifacts-credprovider#173]
When try restore the nuget package i received the following:

`
Step 12/19 : RUN dotnet restore --configfile "NuGet.Config"
 ---> Running in 9fa63f737600
  Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/***/2e8805f8-fae2-4710-8fc1-3fc00f2c5e6e/_packaging/6098c654-d8c0-45c7-ba19-cdff51c0e06c/nuget/v3/flat2/microsoft.aspnetcore.httpspolicy/index.json'.
  The SSL connection could not be established, see inner exception.
    Authentication failed because the remote party has closed the transport stream.
  Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/***/2e8805f8-fae2-4710-8fc1-3fc00f2c5e6e/_packaging/69e14ca1-38fe-4f61-97a9-0bb4f84f87e3/nuget/v3/flat2/microsoft.aspnetcore.httpoverrides/index.json'.
  The SSL connection could not be established, see inner exception.
    Authentication failed because the remote party has closed the transport stream.
`

I use [Azure Artifacts](https://github.com/microsoft/artifacts-credprovider#environment-variables) on the Azure Pipeline and it works well but on the desktop docker it doesn't restore.

**Comment by edgarrs** [comment]
Try following the instructions pointed out here:
https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md

Please re-open is this still an issue.
