### ISSUE TITLE
Provider cache gets invalidated very time the proj file changes

### ISSUE THREAD

**Issue by andreesteve** [microsoft/artifacts-credprovider#174]
I noticed that if I change the project file and request another ```dotnet restore``` I need to authenticate again. This is true even if there are no changes to the nuget feed sources.

In our case, we have several Azure DevOps feeds in different projects, which requires several authentication prompts.

Is it possible to configure the auth provider to not require to re-authenticate even after making project changes?

EDIT:
SessionTokenCache env var is enabled:

```
printenv | grep -i NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED
NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED=true
```

**Comment by satbai** [comment]
You could use just one Artifacts feed to authenticate to and set the other feeds as [upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops) to that one feed.
