### ISSUE TITLE
Publish to some package manager(s)

### ISSUE THREAD

**Issue by kimsey0** [microsoft/artifacts-credprovider#175]
The easiest way to install is currently to download and run a helper script for either PowerShell or Bash, but:

1. There's no standardized way to automatically install from the command line. You can try downloading and running the helper script from raw.githubusercontent.com, but there's no guarantee that the URL won't break, and no permalink [like for PowerShell](https://aka.ms/install-powershell.ps1).
2. There's no way to check for or be notified of updates, except for fetching and parsing the GitHub releases page.

To allow for easier installation and updating, the Azure Artifacts Credential Provider could be published to some package managers, for example Chocolatey or OneGet/PackageManagement for Windows, a Debian repository for (Debian-based) Linux, and Homebrew for Mac.

**Comment by jmyersmsft** [comment]
That'd be handy, but we don't really have the resources on the team to set up and maintain that right now, sorry.

**Comment by kimsey0** [comment]
That's fair enough. Could you perhaps get a permanent aka.ms link for the installation script?

**Comment by johnterickson** [comment]
Related #158 on adding aka.ms permalink

**Comment by drdamour** [comment]
any changes on this? not having it via chocolatey is a real hinderance to my dev team
