### ISSUE TITLE
Get 401 Unthorized after update PAT in VSS_NUGET_EXTERNAL_FEED_ENDPOINTS

### ISSUE THREAD

**Issue by BonnieWei** [microsoft/artifacts-credprovider#176]
Hi experts. We currently got a 401 issue when using credential provider to access nuget feeds.
Before we update our PAT, it works fine. 
But after we update the PAT in the VSS_NUGET_EXTERNAL_FEED_ENDPOINTS, we start to get 401 unauthorized error when trying to access the feeds listed in it. 
The error occurred first continuously then randomly then seems to be working fine after 1 day.

I'm wondering if there are any caches and how to disable them to avoid further update pat causing this error?

We set the the following system variables:
NUGET_PLUGIN_PATHS = D:\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe

VSS_NUGET_EXTERNAL_FEED_ENDPOINTS = {"endpointCredentials": [
{"endpoint": "https://<xxx>.pkgs.visualstudio.com/_packaging/<aaa>/nuget/v3/index.json","username":"optional","password":[pat]},
{"endpoint":"https://<xxx>.pkgs.visualstudio.com/_packaging/<aaa>/nuget/v3/index.json","username":"optional","password":[pat]},
{"endpoint":"https://<xxx>.pkgs.visualstudio.com/_packaging/<aaa>/nuget/v3/index.json","username":"optional","password":[pat]}
]}

**Comment by jmyersmsft** [comment]
There are no credential caches when using VSS_NUGET_EXTERNAL_FEED_ENDPOINTS. PATs should start working immediately. There are local package caches however. If it's possible that another process using a different authentication mechanism is filling that cache, the successes may actually be spurious because NuGet won't attempt to contact the server unless it has something to do.

Can you give a little more detail about your scenario and why you're using VSS_NUGET_EXTERNAL_FEED_ENDPOINTS directly?

**Comment by BonnieWei** [comment]
We want to use PAT to access the nuget feed to upload and download nuget packages. Is there any other better ways instead of using NUGET_PLUGIN_PATHS and VSS_NUGET_EXTERNAL_FEED_ENDPOINTS?

We actually didn't clear the local cache after we update the PAT. Will it be a problem to access the local cache with new PAT when the local cache is filled by the old PAT?

**Comment by BonnieWei** [comment]
One more question is that the detailed exception is:

Unable to find version '900.3.986' of package 'ABCD.dll'.
      C:\Users\[username]\.nuget\packages\: Package 'ABCD.dll.900.3.986' is not found on source 'C:\Users\[username]\.nuget\packages\'.
      https://<a>.pkgs.visualstudio.com/_packaging/Bing/nuget/v3/index.json: Error downloading 'ABCD.dll.900.3.986' from 'https://<a>.pkgs.visualstudio.com/_packaging/eab9af41-a533-4e2f-8f8b-ea7b659298f6/nuget/v3/flat2/ABCD.dll/900.3.986/ABCD.dll.900.3.986.nupkg'.
      Response status code does not indicate success: 401 (Unauthorized).
      https://<b>.pkgs.visualstudio.com/_packaging/Public/nuget/v3/index.json: Error downloading 'ABCD.dll.900.3.986' from 'https://<b>.pkgs.visualstudio.com/_packaging/30fd24f2-f84a-4bcb-98bf-ea78e6d38134/nuget/v3/flat2/ABCD.dll/900.3.986/ABCD.dll.900.3.986.nupkg'.
      Response status code does not indicate success: 401 (Unauthorized).
      https://<c>.pkgs.visualstudio.com/_packaging/Internal/nuget/v3/index.json: Error downloading 'ABCD.dll.900.3.986' from 'https://<c>.pkgs.visualstudio.com/_packaging/e62a8975-9c58-482a-a703-59159d24441e/nuget/v3/flat2/ABCD.dll/900.3.986/ABCD.dll.900.3.986.nupkg'.
      Response status code does not indicate success: 401 (Unauthorized).

Looks like we are trying to get the package directly from the nuget feed instead of the local cache in this case.

**Comment by jmyersmsft** [comment]
I meant the local cache may be *hiding* problems on some runs, not causing them. 

My question about scenario was more about _why_ you are using a PAT rather than the interactive prompt, automatic authentication in Azure Pipelines, etc.

**Comment by BonnieWei** [comment]
Our service is like a build service. Customer upload their code and package locations, we automatically download them and build the user code. So interactive mode is not an option. And since our coding language is a custom one so I don't think Azure pipeline will support it .

I get what you mean by saying the local cash. You mean if we got another service downloading the packages to local cache, the problem of unauthorized might still exists but hidden by local cache. Right? Thanks for raising this. We'll double check that.

**Comment by jmyersmsft** [comment]
Got it. Just wanted to make sure we couldn't resolve this by doing something easier that doesn't involve manually configuring PATs.

Yeah, that's what I meant. 

If you run NuGet with "detailed" verbosity, you should see some logs about "CredentialProvider" which should tell you if it's using the configured credentials at all. You may want to generate another new PAT, making sure it has the packaging read (and write if necessary for your scenario) scopes when you create it, and then put it in your configuration, making sure you got the whole PAT with no extra characters, and that the JSON remains well-formed.

**Comment by BonnieWei** [comment]
We'll try run the nuget with "detailed" verbosity to see the credential provider it's using.
Are there any special cases we need to pay attention when we use these two environment variables?

**Comment by BonnieWei** [comment]
Today, I hit the issue of 401 again. The error starts with the credential error:

Error: Problem starting the plugin 'D:\\local\\Temp\\plugins\\netfx\\CredentialProvider.Microsoft\\CredentialProvider.Microsoft.exe'. Plugin 'CredentialProvider.Microsoft' failed within 9.042 seconds with exit code -1.
Problem starting the plugin 'D:\\local\\Temp\\plugins\\netfx\\CredentialProvider.Microsoft\\CredentialProvider.Microsoft.exe'. Plugin 'CredentialProvider.Microsoft' failed within 9.042 seconds with exit code -1.
  Plugin 'CredentialProvider.Microsoft' failed within 9.042 seconds with exit code -1.
  A task was canceled.

Do we have any clue why this happened?

**Comment by tarifrr** [comment]
I am getting a **401 (Unauthorized)** as well upon `dotnet restore`. Using a Ubuntu based Build agent for running automated build jobs. 

Steps performed:

1) Installed credentials provider
2) Exported **NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED** and **VSS_NUGET_EXTERNAL_FEED_ENDPOINTS** both on the build machine manually and also through the build pipe itself with the proper JSON.
3) Still fails to pull packages from external feeds

However, the build pipe works **temporarily** when I clone the repo afresh and perform a `dotnet restore` manually by ssh-ing into the build machine.

Any ideas where I am going wrong?

**Comment by satbai** [comment]
Regarding the "Problem starting the plugin" error, make sure you use the latest version of this cred provider and nuget/dotnet. There were bug fixes around this area that are fixed in nuget 5.5.x.
