### ISSUE TITLE
Constant timeouts when using CredProvider 

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/artifacts-credprovider#178]
[nugetpluginlog.txt](https://github.com/microsoft/artifacts-credprovider/files/4412191/nugetpluginlog.txt)

Dotnet sdk 3.1.100
Seeing a lot of timeouts such as:

`The HTTP request to 'GET <URL>' has timed out after 100000ms. `
and
`[CredentialProvider]Timed out waiting for plug-in operations to complete`

I've attached a log showing a section of these. This is an internal project so please contact me if more information is needed.

**Comment by satbai** [comment]
I can see from the logs that there are a lot of parallel requests and that nuget 5.4.0.3 is being used. There were some bug fixes in nuget around this area and the latest fixes are in nuget 5.5.x. Could you try updating the nuget version and see if it resolves the timeouts? 

Also, I'm not sure if either of these timeout variables will help, but it may be worth a try if updating nuget doesn't fix this. Set these nuget environment variables to 20 seconds, for example.
NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS
NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS

**Comment by pieandcakes** [comment]
@satbai how important do you think the Nuget 5.5.x will be in this scenario? This is an online environment that I don't control so I don't know if I can get the updated Nuget version on there.

I will change the timeouts and see if that improves the experience.

**Comment by satbai** [comment]
There's a threadpool starvation issue fix on nugete 5.5. Version 5.4 already has some fixes https://github.com/NuGet/Home/issues/8528#issuecomment-556312712
