### ISSUE TITLE
Cred helper not used with Nuget (mono)

### ISSUE THREAD

**Issue by rsouthgate** [microsoft/artifacts-credprovider#184]
I attempted to install the cred helper on Mac OS. Integration works fine with `dotnet` cli. MSBuild and Nuget both fail for a .net framework project. It appears as though the cred helper isn't picked up by these tools. 

I note the version of Nuget (and the latest available via `nuget update -self`) is 5.4.0 and the docs indicate some better handling of timeouts etc in 5.5+ but there is no mono version of 5.5/5.6?

Sample output from a `nuget restore`

```zsh
% nuget restore         
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/15.0/bin'.
Restoring NuGet package <redacted>.6.0.47.
Restoring NuGet package <redacted>.6.0.47.
Restoring NuGet package <redacted>.6.0.47.
Please provide credentials for: https://pkgs.dev.azure.com/<redacted>/nuget/v3/index.json
UserName: <redacted>
Password: ********
Please provide credentials for: https://pkgs.dev.azure.com/wwnz/_packaging/Olympic.OnlineShopping/nuget/v3/index.json
UserName: <redacted>
Password: ********
Please provide credentials for: https://pkgs.dev.azure.com/wwnz/_packaging/Olympic.OnlineShopping/nuget/v3/index.json
UserName: <redacted>
Password: ********
Please provide credentials for: https://pkgs.dev.azure.com/wwnz/_packaging/Olympic.OnlineShopping/nuget/v3/index.json
UserName: <redacted>
Password: ********
  GET https://api.nuget.org/v3-flatcontainer/o<redacted>/6.0.47/olympic.search.plugins.6.0.47.nupkg
  GET https://api.nuget.org/v3-flatcontainer/<redacted>/6.0.47/olympic.search.website.6.0.47.nupkg
Please provide credentials for: https://pkgs.dev.azure.com/<redacted>/nuget/v3/index.json
UserName:   NotFound https://api.nuget.org/v3-flatcontainer/<redacted>.6.0.47.nupkg 780ms
  NotFound https://api.nuget.org/v3-flatcontainer/<redacted>.6.0.47.nupkg 934ms
WARNING: Unable to find version '6.0.47' of package '<redacted>'.
  /Users/<redacted>/.nuget/packages/: Package '<redacted>.6.0.47' is not found on source '/Users/<redacted>/.nuget/packages/'.
  https://pkgs.dev.azure.com/<redacted>/nuget/v3/index.json: Unable to load the service index for source https://pkgs.dev.azure.com/<redacted>/nuget/v3/index.json.
  Response status code does not indicate success: 401 (Unauthorized).
  https://api.nuget.org/v3/index.json: Package '<redacted>.6.0.47' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://pkgs.dev.azure.com/<redacted>/nuget/v3/index.json: Unable to load the service index for source https://pkgs.dev.azure.com/<redacted>/nuget/v3/index.json.
  The HTTP request to 'GET https://pkgs.dev.azure.com/<redacted>/nuget/v3/index.json' has timed out after 100000ms.
```

**Comment by satbai** [comment]
I think the problem here is the msbuild version: "using msbuild version '15.0'". The version of msbuild that supports this plugin cred provider is '15.8.166.59604' as mentioned in the [readme](https://github.com/microsoft/artifacts-credprovider#msbuild-on-windows).

**Comment by satbai** [comment]
Also note that NuGet 5.4.0 still works with this cred provider. It just doesn't have the latest bug fixes and may run into problems in some cases (especially if you have a lot of different sources you're restoring from and nuget is running all those requests in parallel). Although there should be workarounds for those problems as well so the plugin is not unusable even if you use a version earlier than 5.5.x as long as it's higher than 4.8.0.5385.

**Comment by rsouthgate** [comment]
Ah I had not properly read the instructions! Thanks for that. MSBuild version looks to be tied to Vis Studio install on a mac and even the preview channel only includes 15.0... I am assuming this is not going to be possible until mono updates this dependency?

**Comment by satbai** [comment]
I see, yeah, I don't know if you're able to update MSBuild somehow independently from VS updates on Mac, or, if you're able to run a newer version of nuget.exe on mono without using MSBuild under the covers. I'm definitely not an expert with Mac or mono though, so I don't know if either of those are possible. 

When it comes to the MSBuild version on Visual Studio on Mac, you may want to open an issue on Visual Studio on Mac to get clarity on whether it'll be updated soon or if there's a way to update it. Or if the problem is that mono doesn't support a newer version of msbuild, mono repo may be the right place to file the issue.

You mentioned you got it working with dotnet. Is that a sufficient workaround?

**Comment by rsouthgate** [comment]
For this project I will just use long lived Personal Access Tokens and I’ve raised an issue with VS for Mac team requesting an update on MS build. Thanks.

**Comment by KirillOsenkov** [comment]
@radical FYI
