### ISSUE TITLE
Mac install instructions don't include netfx, only netcore

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/artifacts-credprovider#186]
I've just wasted a few hours investigating why msbuild /r doesn't restore packages from a private Azure DevOps feed on a Mac.

Turns out I installed the `netcore` plugin into `.nuget/plugins` but I didn't install `netfx`. The automated script for Mac also doesn't include it. I had to manually copy it.

We really need to include both `netcore` and `netfx` plugins by default.

P.S. I used the instructions here:
https://github.com/microsoft/artifacts-credprovider#installation-on-linux-and-mac

**Comment by KirillOsenkov** [comment]
@radical

**Comment by KirillOsenkov** [comment]
Just to help prioritize this, it's a source of a lot of friction and pain in the Visual Studio for Mac ecosystem. If we want our users to have a smooth experience working with Azure DevOps, we need to fix this.

I've also filed a bug against Mono to install both providers on Mac by default:
https://github.com/mono/mono/issues/19687

**Comment by satbai** [comment]
I agree that the script should at least have the option to install the netfx version if not install it by default. I think we originally made a wrong assumption in the script that Linux/Mac users would be using dotnet, which uses the netcore version. But since nuget.exe can be used with mono it does make sense that we provide a script that installs netfx as well.

**Comment by Cheesebaron** [comment]
Is there any progress on this? Telling people to do a bunch of manual steps to get nuget restore to work is not super nice.

**Comment by KirillOsenkov** [comment]
Can we please at least include a link to the corresponding Dev Community issue here?

@satbai

**Comment by Cheesebaron** [comment]
Doesn't look like it was actually moved there. The bot just closed this issue...
