### ISSUE TITLE
Using the credentials of NuGetAuthenticate task on build agents outside azure hosted pool

### ISSUE THREAD

**Issue by rahburma** [microsoft/artifacts-credprovider#189]
I am trying to find an alternative to using PAT on build agent outside azure hosted pool.
If I run NugetAuthenticate task on a hosted VM, I can access VSS_NUGET_ACCESSTOKEN and VSS_NUGET_URI_PREFIXES environment variable. I tried to pass these variables to a script which runs on a VM outside azure hosted pool. I am accessing this VM(non hosted) from within the hosted VM.
However, I don't see that the variables are injected into the credential provider and I get 401 unauthorized error. Please note that variables are still active since the scope of the job in yaml file is not over yet.
As per documentation, I know that VSS_NUGET_EXTERNAL_FEED_ENDPOINTS env. variable is supposed to be used in this scenario. I tried replacing the password with VSS_NUGET_ACCESSTOKEN but it didn't work since it seems the token is too large for credential provider to consume.
I would like to know if the combination of VSS_NUGET_ACCESSTOKEN and VSS_NUGET_URI_PREFIXES can work in build agents outside hosted pool.

**Comment by magleaso** [comment]
Is this build agent an Azure Pipelines self-hosted agent? if so, have you tried just running the NuGet authenticate task on the self-hosted agent?

**Comment by rahburma** [comment]
Yes running NuGet authenticate task on the self-hosted agent sets VSS_NUGET_ACCESSTOKEN and VSS_NUGET_URI_PREFIXES environment variables. Can I copy these variables to a non-hosted agent and feed it to credential provider there ?

**Comment by rahburma** [comment]
I am closing this issue since the approach that I was trying is indeed possible.
