### ISSUE TITLE
for multiple feeds, reuse creds if same AAD tenant

### ISSUE THREAD

**Issue by rrelyea** [microsoft/artifacts-credprovider#195]
Per meeting with @jmyersmsft @satbai and Aurelie, one improvement that came up that may help the recent dogfooding effort with AACP is:

device flow prompts once per feed, where it should be able to use the same creds, in most cases, if same AAD Tenant.

**Comment by samuelkoppes** [comment]
The best way to resolve this is to ensure you are using a single feed from a particular client.
