### ISSUE TITLE
Unable to resolve the Credential Provider zip file

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/artifacts-credprovider#197]
Our AzDO CI failed with
```
installcredprovider.ps1 : Unable to resolve the Credential 
Provider zip file from https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest
```

From reading of the script the error is in this line:
https://github.com/microsoft/artifacts-credprovider/blob/3902a1eadc037829d4a161d287d8579f1fb2168e/helpers/installcredprovider.ps1#L90

Unfortunately it doesn't print details as to what exception has occurred. Would it be possible to add better diagnostic logging in case of an error in this area?

Otherwise I'm not sure how to investigate this further.

**Comment by johnterickson** [comment]
Hi @KirillOsenkov - good to hear from you! This makes sense.  We'd welcome a PR here 😇.  Also if you want to add `-MaximumRetryCount` to the I-WR, it could help. 

@phil-hodgson would also like to understand why you are running this as part of your CI.

**Comment by KirillOsenkov** [comment]
I honestly have no idea why the CI does what it does - I didn't set it up. Would really appreciate if someone could take a look and fix it to do the right thing!

The PR I have that failed the CI is still outstanding...

**Comment by AmadeusW** [comment]
Just wanted to reach out and say that this issue keeps happening and it is impacting our team and others.
Does anyone know why this happens?
```
VERBOSE: GET https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1 
with 0-byte payload
VERBOSE: received 6098-byte response of content type text/plain; charset=utf-8
VERBOSE: Using Microsoft.NetCore2.NuGet.CredentialProvider.zip
Fetching release https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest
VERBOSE: GET https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest with 0-byte payload
C:\a\_tool\vs-platform\tools\installcredprovider.ps1 : Unable to resolve the Credential Provider zip file from 
https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest
```

**Comment by KirillOsenkov** [comment]
@johnterickson @herenhuang @phil-hodgson could we please include a link to the Dev Community issue that is tracking this?

**Comment by johnterickson** [comment]
There's lots of ways that network hiccups could cause failures.  Since the script is idempotent, I recommend just running it twice, e.g.:
```
iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"; iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"
```

**Comment by KirillOsenkov** [comment]
Would it make sense to put in a retry into the script itself?

**Comment by KirillOsenkov** [comment]
And the script should be printing the exception callstack, so we at least have visibility into the nature of the issue.
