### ISSUE TITLE
CredProvider as dotnet global tool

### ISSUE THREAD

**Issue by siby-george** [microsoft/artifacts-credprovider#206]
If we can install Cred provider via dotnet global tool install feature. it will be simplify docker build a lot. 

eg.
Dotnet tool install CredProvider
dotnet credprovider endpointCredentials <endpoint1> <username> <pwd>
dotnet credprovider endpointCredentials <endpoint2> <token>

**Comment by cacizi41** [comment]
I second this. An unified way of installing will make build a lot easier.

**Comment by irperez** [comment]
Yes, please.  This can be a brutal setup.

**Comment by gregorylyons** [comment]
Delivering this would unblock adopting of this tool for our build process.
