### ISSUE TITLE
Using PATs with docker is overly manual

### ISSUE THREAD

**Issue by gunnim** [microsoft/artifacts-credprovider#209]
We have Azure ADAL set up for SSO, and are looking to use docker as a build environment. We have a private azure artifacts feed we need to access during NuGet restore. One solution is proposed [here](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider). It however involves manually managing a PAT. 

I'm pretty close to a solution that instead calls artifacts-credprovider from the command line and requests a session token, parsing the output and providing that token to the docker image in a similar way.
That way we can generate a script for re-use across the office that would utilise azure adal sso for authentication.

The fact that I need to parse the text output from artifacts credential provider and manage potentially invalid credentials returned from cache via the IsRetry cli param however lends me to believe this path is completely unsupported?

**Comment by edgarrs** [comment]
@gunnim,  the guidance from the dotnet-docker document is our supported scenario. We will revisit the suggestion in the future.
