### ISSUE TITLE
Is there a similar version of this tool for Java, NPM or Python?

### ISSUE THREAD

**Issue by bbarman4u** [microsoft/artifacts-credprovider#212]
Is there a similar version of this tool for Java(Maven, Gradle), NPM or Python?

**Comment by omokoh** [comment]
Hey, 
What tool do you mean?
Can you share with us a scenario of what you are trying to do?

**Comment by edgarrs** [comment]
@bbarman4u , Here are the tools we have:
- nmp: https://www.npmjs.com/package/vsts-npm-auth
- python: https://github.com/microsoft/artifacts-keyring
- java: we don't have a tool but you can set the PAT directly in the pom.xml and settings.xml files

**Comment by bbarman4u** [comment]
Thank you @edgarrs  for the suggestions.

**Comment by amih90** [comment]
[vsts-npm-auth](https://www.npmjs.com/package/vsts-npm-auth) is not cross platform.
will be nice to have similar wrapper as python-conda to avoid managing PAT for npm on Linux.
