### ISSUE TITLE
Logins to https://microsoft.com/devicelogin not working

### ISSUE THREAD

**Issue by simonauner** [microsoft/artifacts-credprovider#216]
Running on Ubuntu 20.04.1 LTS I used to be able to use the artifacts-credprovider to sign in to get Nuget packages from our Azure Artifacts repository, but now it's not working anymore. I tried installing the credprovider again but that didn't help.

```console
$ dotnet --version                                                                                                     1
3.1.403
```
This is what I try to do:

```console
$ dotnet list package --outdated --interactive
The following sources were used:
   https://pkgs.dev.azure.com/***/_packaging/***/nuget/v3/index.json
   https://api.nuget.org/v3/index.json

log  :     [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/***/_packaging/***/nuget/v3/index.json
log  :     [CredentialProvider]ATTENTION: User interaction required. 
log  : 
log  :     **********************************************************************
log  : 
log  :     To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ABC123 to authenticate.
log  : 
log  :     **********************************************************************
```

I copy the code and paste it on https://microsoft.com/devicelogin, which takes me to a login screen, where I sign in.

When I do that, this is what happens:

```console
info :     [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'ADAL Device Code'
info :     [CredentialProvider]VstsCredentialProvider - Attempting to exchange the bearer token for an Azure DevOps session token.
log  :     [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/***/_packaging/***/nuget/v3/index.json
log  :     [CredentialProvider]ATTENTION: User interaction required. 
log  : 
log  :     **********************************************************************
log  : 
log  :     To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DEF456 to authenticate.
log  : 
log  :     **********************************************************************
```

Any ideas what might be going wrong? This used to work :(

**Comment by josmithua** [comment]
I am also having this issue. It just keeps asking for me to authenticate. `dotnet 5.0.100` on macOS

**Comment by josmithua** [comment]
If I run the Credential Plugin in standalone mode it works:

`dotnet exec ~/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll -U https://pkgs.dev.azure.com/<org_name>/_packaging/SharedLibraries/nuget/v3/index.json -V Verbose`

**Comment by aDisplayName** [comment]
Same thing here, using Windows 10 2004 and Powershell.
Couple months ago, we could were using ```dotnet restore --interactive``` command restore the packages to local folder in powershell script from the Azure DevOps private feeds. Now it does not work anymore.

After successfully logged-in using DeviceFlow in Microsoft Edge, the restore still failed with status code 401.

```
Determining projects to restore...
      [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/xxx/_packaging/yyy/nuget/v3/index.json
      [CredentialProvider]ATTENTION: User interaction required.

      **********************************************************************

      To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
      **********************************************************************

C:\Program Files\dotnet\sdk\3.1.401\NuGet.targets(128,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/xxx/_packaging/yyy/nuget/v3/index.json. [C:\Users\mycode.sln]
C:\Program Files\dotnet\sdk\3.1.401\NuGet.targets(128,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\mycode.sln]
```

First we thought it might be because we have upgraded to dotnet 5.0. We did it again in a machine only use dotnet 3.1, and get the same result.

**Comment by minkom-ms** [comment]
I'm also seeing this on  Windows. It's a shame no one has even bothered to look at this since November. I was able to find a workaround, at least on Windows. Setting NUGET_CREDENTIALPROVIDER_MSAL_ENABLED environment variable did the trick.

`$env:NUGET_CREDENTIALPROVIDER_MSAL_ENABLED="true"`

**Comment by josmithua** [comment]
Setting the environment variable didn’t work for me on macOS

**Comment by qidydl** [comment]
This is broken on Windows as well (Windows 10 20H2, .NET SDK 5.0.201). It just keeps prompting for credentials over and over--it is generating access tokens but not using them for some reason. There are no error messages printed anywhere I can see. I get the same behavior whether I set `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED` to true or not. Visual Studio doesn't have a problem at all, and we have internal packages we have to use, so this effectively blocks all sorts of command-line-only functionality like the vulnerable and outdated package checks.

**Comment by SaaadSaadAl** [comment]
Gh

**Comment by Granjow** [comment]
Same results as the OP here on Ubuntu with dotnet 3.1.408 …

**Comment by abbottdev** [comment]
Has anyone got a link to an issue that lists this on the above site? I'm getting this with macOS and can't figure it out at all.

**Comment by tillig** [comment]
I'm still getting 401 issues and device code flow problems so I [added an item to the Developer Community](https://developercommunity.visualstudio.com/t/azure-artifacts-credential-provider-unable-to-auth/1519587) to try and capture it. I'm not sure if my issue is specifically _this one_, though I do find `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED=true` works for me and it doesn't for everyone.
