### ISSUE TITLE
dotnet add package without version does not work

### ISSUE THREAD

**Issue by hoksource** [microsoft/artifacts-credprovider#218]
I just 
- migrated to .net 5
- updated my visual studio 2019 (MSBUILD).
- installed replaced my nuget to 5.7
- recoied zip the windows nuget cred plugins to .nuget folder

i upload my packages to azure devops artifact.

whenever i call:
```
dotnet add package {package}
dotnet add package {package} --interactive
dotnet add package {package} -s {my_artifact_url} --interactive
```

even if package is available at global nuget. It references my azure devops artifact url and gives a 401

i have to use
```
dotnet add package {package} -v {version}
```

before the package gets added. 
(private or nonprivate nuget source. with or without -s. with or without --interactive)

I'm not sure if this is a bug. But from now i have to add the version -v all the time.

**Comment by DrakeLambert** [comment]
I have this same issue.
artifacts-credprovider version: `0.1.25`
dotnet sdk versions:
```
2.1.505
2.1.519
2.1.700
2.2.300
2.2.401
3.0.100
3.1.102
3.1.201
5.0.101
```
