### ISSUE TITLE
Artifacts-credprovider (VSS_NUGET_EXTERNAL_FEED_ENDPOINTS) does not work with .Net 5 SDK

### ISSUE THREAD

**Issue by Gladskih** [microsoft/artifacts-credprovider#220]
I had my image built on sdk3.1 according to your [instruction](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider) but on sdk5.0 it doesn't work:

> /usr/share/dotnet/sdk/5.0.100/NuGet.targets(131,5): error :   GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (SPNEGO cannot find mechanisms to negotiate).

I already made `echo $VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` and it's still correct.
I tried to remove `ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` and `ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true`
I tried on debian and alpine based SDK images.
I tried to add `ENV NUGET_AUTHENTICATION_TYPES=basic`.
It looks like updated SDK just ignores `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS ` or Artifacts-credprovider or `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER`.

With `--verbosity diag` on `dotnet restore` I get stacktrace:

> ---> System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (SPNEGO cannot find mechanisms to negotiate).
>                         at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
>                         at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
>                         at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
>                         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>                         at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
>                         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>                         at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>                         at NuGet.Protocol.ProxyAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>                         at NuGet.Protocol.HttpSourceAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>                         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
>                         at NuGet.Protocol.HttpRetryHandler.<>c__DisplayClass2_1.<<SendAsync>b__0>d.MoveNext()
>                      --- End of stack trace from previous location ---
>                         at NuGet.Protocol.TimeoutUtility.StartWithTimeout[T](Func`2 getTask, TimeSpan timeout, String timeoutMessage, CancellationToken token)
>                         at NuGet.Protocol.HttpRetryHandler.SendAsync(HttpRetryHandlerRequest request, String source, ILogger log, CancellationToken cancellationToken)
>                         at NuGet.Protocol.HttpSource.GetThrottledResponse(Func`1 requestFactory, TimeSpan requestTimeout, TimeSpan downloadTimeout, Int32 maxTries, Boolean isRetry, Boolean isLastAttempt, Guid sessionId, ILogger log, CancellationToken cancellationToken)
>                         at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
>                      --- End of stack trace from previous location ---
>                         at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
>                         at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
>                         at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
>                         at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
>                         --- End of inner exception stack trace ---
>                         at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
>                         at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
>                         at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
>                         at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
>                         at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
>                         at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
>                         at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
>                         at NuGet.Commands.SourceRepositoryDependencyProvider.EnsureResource()
>                         at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryCoreAsync(LibraryRange libraryRange, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
>                         at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext()
>                      --- End of stack trace from previous location ---
>                         at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
>                         at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass9_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
>                      --- End of stack trace from previous location ---
>                         at NuGet.DependencyResolver.ResolverUtility.FindLibraryFromSourcesAsync(LibraryRange libraryRange, IEnumerable`1 providers, Func`2 action)
>                         at NuGet.DependencyResolver.ResolverUtility.FindLibraryByVersionAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 providers, SourceCacheContext cacheContext, ILogger logger, CancellationToken token)
>                         at NuGet.DependencyResolver.ResolverUtility.FindPackageLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
>                         at NuGet.DependencyResolver.ResolverUtility.FindLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, IEnumerable`1 projectProviders, IDictionary`2 lockFileLibraries, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
>                         at NuGet.DependencyResolver.ResolverUtility.FindLibraryEntryAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, RemoteWalkContext context, CancellationToken cancellationToken)
>                         at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge, TransitiveCentralPackageVersions transitiveCentralPackageVersions)
>                         at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge, TransitiveCentralPackageVersions transitiveCentralPackageVersions)
>                         at NuGet.DependencyResolver.RemoteDependencyWalker.WalkAsync(LibraryRange library, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, Boolean recursive)
>                         at NuGet.Commands.ProjectRestoreCommand.WalkDependenciesAsync(LibraryRange projectRange, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, RemoteDependencyWalker walker, RemoteWalkContext context, CancellationToken token)
>                         at NuGet.Commands.ProjectRestoreCommand.TryRestoreAsync(LibraryRange projectRange, IEnumerable`1 frameworkRuntimePairs, NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteDependencyWalker remoteWalker, RemoteWalkContext context, Boolean forceRuntimeGraphCreation, CancellationToken token, TelemetryActivity telemetryActivity)
>                         at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity)
>                         at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
>                         at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
>                         at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
>                         at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
>                         at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
>                         at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
>                         at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken)
>                         at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log) (TaskId:36)

**Comment by FrenchTastic** [comment]
Hi everyone !

Same issue here, since I updated to .Net 5, I cannot use my private Nuget Feed with credential provider.

**Comment by Gladskih** [comment]
I have workaround: add restore stage on sdk3.1 to docker multistage build and then copy packages to build stage.

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS restore
ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true
RUN apk add curl
RUN curl -fsSL https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh | sh
ARG nuget_PAT
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS \
    "{\"endpointCredentials\": [{\"endpoint\":\"https://my-feed/nuget/v3/index.json\", \"password\":\"${nuget_PAT}\"}]}"
RUN apk add ca-certificates
WORKDIR /src
COPY ["ca-bundle.crt", "/usr/local/share/ca-certificates/"]
RUN update-ca-certificates
COPY ["nuget.config", "my-project/"]
COPY ["my-project/my-project.csproj", "my-project/"]
ENV NUGET_PACKAGES=/packages
RUN dotnet restore "my-project/my-project.csproj" --configfile "my-project/nuget.config"

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src
ENV NUGET_PACKAGES=/packages
COPY --from=restore /packages /packages
COPY . .
WORKDIR "/src/my-project"
RUN dotnet build "my-project.csproj" -c Release -o /app/build
```

**Comment by FrenchTastic** [comment]
Thanks for your workaround.

Sound silly (me), but I did'nt know that "dotnet cli" had command for adding TFS Nuget Feed (works with PAT).
So now, instead of using Artifact-cred provider I add just :

`RUN dotnet nuget add source https://myfeed --name "myfeed" --username "whatever" --password="mypat" --store-password-in-clear-text --valid-authentication-types "basic"`

I don't know if this wiil be useful for you.

Have a great day.

**Comment by Gladskih** [comment]
For me  `dotnet nuget add source` leads to the same error "SPNEGO cannot find mechanisms to negotiate"

**Comment by Gladskih** [comment]
In combination with `dotnet nuget add source ` must not be used nuget.config

**Comment by scabana** [comment]
Since updating to .net 5, I'm also having issues. 

We're using a `NuGet.config` file at root of sln.
`dotnet restore` works
`dotnet add package Microsoft.Extensions.DependencyInjection` on one of the projects within the folder structure gives a 401
`dotnet add package Microsoft.Extensions.DependencyInjection --interactive` does not trigger the login flow.

```
❯ dotnet add package Microsoft.Extensions.DependencyInjection                    
  Determining projects to restore...
  Writing C:\Users\***\AppData\Local\Temp\tmp96C9.tmp
info : Adding PackageReference for package 'Microsoft.Extensions.DependencyInjection' into project 'D:\Repos\***\src\***\***.csproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.extensions.dependencyinjection/index.json
info :   GET https://pkgs.dev.azure.com/stratocast/_packaging/17da97ff-7b2f-4be7-85fd-d42fd1c474da/nuget/v3/registrations2-semver2/microsoft.extensions.dependencyinjection/index.json
info :   Unauthorized https://pkgs.dev.azure.com/***/_packaging/***/nuget/v3/registrations2-semver2/microsoft.extensions.dependencyinjection/index.json 543ms
error: Response status code does not indicate success: 401 (Unauthorized).
```

I have used --interactive flag on restore to login the first time. 

- CredentialProvider.Microsoft.dll dll: 0.1.24.0
- NuGet Version: 5.8.0.6930
- Microsoft Visual Studio Enterprise 2019 Version 16.8.1
- On windows 10 2004

**Comment by irperez** [comment]
@FrenchTastic 's solution worked for me.  See my issue and resulting docker script in issue #228

**Comment by totollygeek** [comment]
This works in Docker, but I have a Linux build agent, where I run a simple `dotnet restore` using [Nuke](https://github.com/nuke-build/nuke). I am using the credentials provider inside our `build.ps1` script which runs Nuke, but now it fails with 5.0. I don't want to add feeds with PAT in clear text on my build agent. Any suggestions?

**Comment by Gladskih** [comment]
@totollygeek How did you authenticate before (with cred manager)? It still need some kind of secret. So maybe the problem is not new.

**Comment by totollygeek** [comment]
We are using the cred-provider with the PAT in the environment variable of the process, which is doing a build. It seemed to be a more secure solution than keeping it in a file. We can of course create a temp `NuGet.config`, store it there with `dotnet nuget` and after the build is finished, delete the file. But still seems undesirable.

**Comment by totollygeek** [comment]
Sooo, we will not see any progress on this issue, I guess? 🤔
