### ISSUE TITLE
The "dotnet restore --interactive" doesn't work anymore for Azure DevOps private feeds

### ISSUE THREAD

**Issue by aDisplayName** [microsoft/artifacts-credprovider#224]
Couple months ago, we were using ```dotnet restore --interactive``` command restore the packages to local folder in powershell script from the Azure DevOps private feeds. Now it does not work anymore.

After successfully logged-in using DeviceFlow in Microsoft Edge, the restore still failed with status code 401.

```
Determining projects to restore...
      [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/xxx/_packaging/yyy/nuget/v3/index.json
      [CredentialProvider]ATTENTION: User interaction required.

      **********************************************************************

      To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
      **********************************************************************

C:\Program Files\dotnet\sdk\3.1.401\NuGet.targets(128,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/xxx/_packaging/yyy/nuget/v3/index.json. [C:\Users\mycode.sln]
C:\Program Files\dotnet\sdk\3.1.401\NuGet.targets(128,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\mycode.sln]
```

First we thought it might be because we have upgraded to dotnet 5.0. We did it again in a machine only use dotnet 3.1, and get the same result.

**Comment by weijia-ai** [comment]
Does anyone edit the permission of the private feed maybe?

**Comment by nathansoz** [comment]
@aDisplayName could you try setting NUGET_CREDENTIALPROVIDER_MSAL_ENABLED. This worked for me and I opened #233

**Comment by johnterickson** [comment]
See internal ICM 224085642

**Comment by cal5barton** [comment]
Setting the environment variable does not work for me. Any ideas? Seems to have happened after installing .Net 5

**Comment by nathansoz** [comment]
@cal5barton I think you would probably be best served by opening a separate github issue. This ended up being related to an internal issue.

**Comment by nathansoz** [comment]
@cal5barton You do need to have the *very* latest version of the cred provider for that setting to exist. The linked issue #233 ended up being an internal issue, so I'm not sure if the setting will help you out much here.

**Comment by cal5barton** [comment]
@nathansoz I've updated the latest version now. Is this a system variable that is set or is it something that needs to be passed to the credprovider itself?

**Comment by nathansoz** [comment]
> @nathansoz I've updated the latest version now. Is this a system variable that is set or is it something that needs to be passed to the credprovider itself?

It's an environment variable. `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED=true`

**Comment by cal5barton** [comment]
> > @nathansoz I've updated the latest version now. Is this a system variable that is set or is it something that needs to be passed to the credprovider itself?
> 
> It's an environment variable. `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED=true`

Yeah, still not working. Is there an ETA of when this will be resolved or another workaround to get up and going?

**Comment by nathansoz** [comment]
Sorry, I'm not on the team. Just someone who hit a similar issue and this happened to be a workaround.

cc: @johnterickson who might have better points of contact.

**Comment by johnterickson** [comment]
@cal5barton Can you share which error you are seeing?

**Comment by cal5barton** [comment]
When running `dotnet add package MYPACKAGE --interactive` I get the following error:

```
error: Unable to load the service index for source https://pkgs.dev.azure.com/****/****/_packaging/****/nuget/v3/index.json.
error:   Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by pdubb29** [comment]
I'm having the same issue 
Powershell:
`$env:NUGET_CREDENTIALPROVIDER_MSAL_ENABLED`
`dotnet add package <packageName> --interactive`
Output:
`error: Unable to load the service index for source https://pkgs.dev.azure.com/****/****/_packaging/****/nuget/v3/index.json.`
`error:   Response status code does not indicate success: 401 (Unauthorized).`

**Comment by cal5barton** [comment]
@johnterickson If I create a global.json file in my repo that targets version `3.1.406` and run the command it works. I would rather not have to add that file to every repo though. There seems to be something about version `5.0.103` that breaks it.

**Comment by pdubb29** [comment]
I was cleaning out old SDKs in my control panel and found that 5.0.103 is packaged up with VS 
![image](https://user-images.githubusercontent.com/3507458/110144299-6a2f0e80-7d95-11eb-84ef-0bc8705818f9.png)

**Comment by aaronla-ms** [comment]
+1, multiple members of my team have hit this as well.
