### ISSUE TITLE
Already installed Azure Artifacts Credential Provider, but still got 401 error

### ISSUE THREAD

**Issue by weijia-ai** [microsoft/artifacts-credprovider#231]
Hi.... my issue is similar to this https://github.com/microsoft/artifacts-credprovider/issues/63 but not exactly the same.

I have an Azure Artifact built for our team, and I managed to follow [this documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops) using `- task: NuGetAuthenticate@0` to complete the ADO pipeline authentication. The documentation mentioned: " Any Azure Artifacts feeds within your organization will automatically be authenticated. ", and I did see the logs below indicating `- task: NuGetAuthenticate@0` works.
```
Installing the Azure Artifacts Credential Provider (.NET Core) to '/root/.nuget/plugins/netcore/CredentialProvider.Microsoft'. This credential provider is compatible with dotnet SDK 2.1.400 or later.
The credential provider is already installed. If there are package related authentication failures in later steps, consider setting this task's input 'forceReinstallCredentialProvider' to true to force reinstallation.

Installing the Azure Artifacts Credential Provider (.NET Framework) to '/root/.nuget/plugins/netfx/CredentialProvider.Microsoft'. This credential provider is compatible with nuget.exe 4.8.0.5385 or later, and MSBuild 15.8.166.59604 or later.
The credential provider is already installed. If there are package related authentication failures in later steps, consider setting this task's input 'forceReinstallCredentialProvider' to true to force reinstallation.

Setting up the credential provider to use the identity 'Project Collection Build Service (team_name)' for feeds in your organization/collection starting with:
  https://{team_name}.pkgs.visualstudio.com/
  https://pkgs.dev.azure.com/{team_name}/

Finishing: NuGet Authentication
```

However, my team relies on an invoked script to perform docker image build, and inside the script, it will run `dotnet restore`, `dotnet build` , etc. This is the place where I get 401 error. (Note: my team is actually using a python script to build, not a dockerfile.)
Shouldn't the script also authenticated along with the pipeline? **Is there a way I can copy the Azure Credential Provider somewhere so the script got authenticated automatically?**
I'm hesitate to use the ADO personal access token, because a)the azure artifact is within my team, there shouldn't be extra token by default... b) once I added ADO PAT, there will be one more secret that need to rotate every once in a while. c) the script invoke link is actually pretty long, something like xxxx.yml -> bbbbb.sh -> ccccc.py -> ddddd.py -> dotnet build. Not sure if I will introduce security issue here by using ADO PAT

Any suggestion for me? I've been digging this for a while and got pretty frustrated...

**Comment by weijia-ai** [comment]
Oh, by the way, I can unblock myself by using `dotnet restore --interactive` on my local machine, but on ADO pipeline it has to be automated. 
Any other flag here can be used for ADO pipeline?

**Comment by satbai** [comment]
If you didn't already, please have a look at the docs on Docker container setup: https://github.com/microsoft/artifacts-credprovider#docker-containers 
NuGet Authenticate uses this Artifacts Cred Provider to help authenticate the nuget/dotnet commands within the pipeline. I think the issue here may be that the NuGet Authenticate task sets up the right environment variables for authentication for the pipeline but the docker isn't reading the pipeline's environment variables but its own environment variables.

**Comment by weijia-ai** [comment]
Thank you @satbai .
I choose to use ADO PAT eventually. I came across that document few days before but not sure how to use `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS`. My understanding is that environment variable was set by Azure Credential Provider and I need to call pass it in somewhere?

But in my case, ADO PAT did solve the problem. 
Thank you again.
