### ISSUE TITLE
Username/Password prompt on push package from AzureDevOps

### ISSUE THREAD

**Issue by amrith-bhogal** [microsoft/artifacts-credprovider#232]
Using this command:

nuget.exe push -Source https://pkgs.dev.azure.com/ (This is taken from the Connect to feed Nuget.exe in Devops in the project setup area)

Please provide credentials for: https://pkgs.dev.azure.com/TBFT/D365FO/_packaging/Annata365/nuget/v3/index.json
UserName: 
Password: 

Unable to load the service index for source https://pkgs.dev.azure.com/
  Response status code does not indicate success: 401 (Unauthorized).

.Net is installed , I have also installed InstallCredProvider.ps1.

Any idea whats going on? As the username and password I am using has access to the Project in DevOps.

**Comment by johnterickson** [comment]
Do not enter a username and password.  That indicates the cred-provider didn't work.  Please provide logs from credprovider install and from nuget.exe push
