### ISSUE TITLE
Credential provider does not send [valid] User-Agent to AAD when performing auth via ADAL/MSAL

### ISSUE THREAD

**Issue by sewillia-msft** [microsoft/artifacts-credprovider#234]
Hey folks,

My org is rolling out some new Conditional Access policies for Azure AD, and the Azure Artifacts provider appears to be causing some unexpected behavior with AAD.

For context, I'm using the credential provider with PowerShellGet/PackageManagement, which appears to be chaining the netcore variant. I'm prompted to do device-code auth as expected, but doing the actual authentication via eSTS yields a conditional-access policy error:

![image](https://user-images.githubusercontent.com/72675818/105111052-eafbaa80-5a74-11eb-9291-5c7bf5e7f0df.png)
(Contrary to what the error suggests, this is a managed device)

After doing a little digging with another engineer, it looks like the credential provider is sending a blank user agent to AAD when performing device-code auth. This causes AAD to fail OS detection and classify the device as "Other" instead of Windows, which subsequently causes eSTS to block the login per our CA policies.

From what I can tell, enabling MSAL via `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED` has no effect.

Tampering with the AAD requests via Fiddler and inserting the default user-agent built via [`NuGetCredentialProvider.Program.UserAgent`](https://github.com/microsoft/artifacts-credprovider/blob/488a3204dd977c337a2d5a2b8ce9693fcc83a960/CredentialProvider.Microsoft/Program.cs#L32-L46) with an appropriate OS comment (e.g. `(Windows NT 10.0; Win64; x64)`) appears to work.

I'm not 100% sure if this is a bug with MSAL or the credential provider proper, but given the number of MSAL-backed apps that are otherwise functioning normally in our tenant I doubt it's an MSAL bug.

**Comment by johnterickson** [comment]
See internal ICM 224085642

**Comment by julioct** [comment]
@johnterickson Is this the reason why my `dotnet restore --interactive` call keeps failing to authenticate against our private feed with this error?

```
C:\Program Files\dotnet\sdk\3.1.405\NuGet.targets(128,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/microsoft/_packaging/Xbox.Streaming/nuget/v3/index.json. 
C:\Program Files\dotnet\sdk\3.1.405\NuGet.targets(128,5): error :   Response status code does not indicate success: 401 (Unauthorized). 
```

We have been using the Artifacts Credentials Provider without issues for several months but we started running into this recently out of nowhere. I'm using an AAD joined machine and all coding happens within VS Code, no Visual Studio.

**Comment by sidiesen** [comment]
I am seeing the same behavior as @julioct for internal feeds, any guidance? Also running in VSCode and sometimes even triggering the build from a commandline script. Maybe also worth noting, we are not using the default dotnet build tasks, but rather our own that calls a separate build script.

**Comment by richardtallent** [comment]
I'm seeing the same issue. Windows 10, managed device, .NET 5. It's a show-stopper for us trying to set up a private nuget feed in ADO Artifacts so we can share libraries between teams.

**Comment by sidiesen** [comment]
@richardtallent the workaround mentioned in this issue seems to have fixed it for us: https://github.com/microsoft/artifacts-credprovider/issues/233
That being said it *should* have been fixed by now, so unsure if it'll still work if you still run into these symptoms.

**Comment by sidiesen** [comment]
Oops sorry, I just noticed I replied to the wrong thread that mentions NUGET_CREDENTIALPROVIDER_MSAL_ENABLED has no effect, my mistake...

**Comment by johnterickson** [comment]
@julioct @richardtallent My second-hand understanding is that if you are using the `device code` flow, then the result authentication will always count as "*not* a managed device" because you are effectively authenticating a different device.

The best bet is to avoid the the device code flow in the first place.

**Comment by tillig** [comment]
I'm still getting 401 issues and device code flow problems so I [added an item to the Developer Community](https://developercommunity.visualstudio.com/t/azure-artifacts-credential-provider-unable-to-auth/1519587) to try and capture it. I'm not sure if my issue is specifically _this one_, though I do find `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED=true` works for me and it doesn't for everyone.
