### ISSUE TITLE
MSAL Cache should share the same token as GCM and VS

### ISSUE THREAD

**Issue by johnterickson** [microsoft/artifacts-credprovider#236]
This will reduce the amount of authentication that will need to happen across tools.  PowerSheell and Az CLI already collude to use this same location.

```
                // The Visual Studio MSAL cache is located at "%LocalAppData%\.IdentityService\msal.cache" on Windows.
                // We use the MSAL extension library to provide us consistent cache file access semantics (synchronisation, etc)
                // as Visual Studio itself follows, as well as other Microsoft developer tools such as the Azure PowerShell CLI.
                const string cacheFileName = "msal.cache";
                string appData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
                string cacheDirectory = Path.Combine(appData, ".IdentityService");
```
https://github.com/microsoft/Git-Credential-Manager-Core/blob/df90676d1249759eef8cec57155c27e869503225/src/shared/Microsoft.Git.CredentialManager/Authentication/MicrosoftAuthentication.cs#L277

**Comment by johnterickson** [comment]
Or maybe https://github.com/microsoft/Git-Credential-Manager-Core/blob/66a573128898b28d46884a643eb6a446ab264562/src/shared/Microsoft.Git.CredentialManager/Authentication/MicrosoftAuthentication.cs#L264

**Comment by johnterickson** [comment]
Looks like maybe we need to align to WAM instead?

**Comment by kyle-rader** [comment]
> Looks like maybe we need to align to WAM instead?
Yes. Adding WAM is probably more useful than defaulting to the shared cache location. However since this doesn't work on Mac yet, it's probably also important to make sure that the cache is setup on Mac. The last time I looked through here I don't remember seeing that get setup.

**Comment by aelij** [comment]
I think you should migrate the auth flow to use Azure.Identity's `DefaultAzureCredential` which attempts to grab a token from: MI, Shared token cache, VS, VS Code, Azure CLI, Azure PowerShell and lastly an interactive browser (or device code).

**Comment by kyle-rader** [comment]
GCM and VS are both moving to WAM which maintains it's own cache internal to the OS. So I think this Issue can be closed as WF. Either ADO Cred provider needs to do some updating, or we could potentially replace it with the soon-to-be open sourced azureauth CLI we're building.

**Comment by johnterickson** [comment]
@bgavrilMS what is "Azure.Identity's DefaultAzureCredential"?

**Comment by kyle-rader** [comment]
This I believe https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet

Kyle Rader (he/him<https://www.mypronouns.org/what-and-why>)
Microsoft.Office.Engineering.Security_Experience
