### ISSUE TITLE
Rate limiting causing frequent CI/PR failures

### ISSUE THREAD

**Issue by AArnott** [microsoft/artifacts-credprovider#244]
A lot of our pipelines are failing with:

> Fetching release https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest
> C:\a\_temp\4701770\installcredprovider.ps1 : Unable to resolve the Credential Provider zip file from https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest

The docs are to use `https://aka.ms/install-artifacts-credprovider.ps1` to get the script.
Is accessing the cred provider directly from github.com fundamentally problematic such that the script should be re-hosted on another machine with a higher rate limit?

**Comment by WardenGnaw** [comment]
This might be a question for the Azure Pipeline Task folks, but it seems like both the NuGet and NuGetAuthenticate Task get both get the CredentialProvider from Azure Storage which has a [very high rate limit](https://docs.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account#scale-targets-for-standard-storage-accounts):  `https://vstsagenttools.blob.core.windows.net/tools/NuGetCredProvider/0.1.24/c.zip` 

References:
- https://github.com/microsoft/azure-pipelines-tasks/blob/ea2446c1cd946fdba8bd7b416c48f5eafa9aa061/Tasks/NuGetAuthenticateV0/make.json#L13
- https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/NuGetCommandV2/make.json#L59

Downside, we would have to make tasks update the URL everytime there is a credential provider update unless we can get a
`https://vstsagenttools.blob.core.windows.net/tools/NuGetCredProvider/latest/c.zip`

**Comment by AmadeusW** [comment]
@WardenGnaw who exactly (which email alias) do we reach out to on the Azure Pipeline Task folks?

That this issue keeps impacting our and other teams.
```
VERBOSE: GET https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1 
with 0-byte payload
VERBOSE: received 6098-byte response of content type text/plain; charset=utf-8
VERBOSE: Using Microsoft.NetCore2.NuGet.CredentialProvider.zip
Fetching release https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest
VERBOSE: GET https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest with 0-byte payload
C:\a\_tool\vs-platform\tools\installcredprovider.ps1 : Unable to resolve the Credential Provider zip file from 
https://api.github.com/repos/Microsoft/artifacts-credprovider/releases/latest
```

**Comment by WardenGnaw** [comment]
I'm not really sure. I'm also just someone impacted by this problem who stumbled upon this issue. 

If you are looking for a solution using `https://vstsagenttools.blob.core.windows.net/tools/NuGetCredProvider`, @satbai who was the person who made this [commit](https://github.com/microsoft/azure-pipelines-tasks/commit/0ec5ba318f411668ab590ec3785b489215250ef4) might know more.

**Comment by AmadeusW** [comment]
Where exactly can we follow resolution of this issue? The developer community link above takes us to a landing page.

**Comment by WardenGnaw** [comment]
Since it was done by a github-action bot, I believe it was a timeout rule with a default message.
See https://github.com/microsoft/artifacts-credprovider/blob/master/.github/workflows/stale.yml

Here's the link to  Developer Community Ticket I created: https://developercommunity.visualstudio.com/t/GitHub-Endpoint-for-NuGet-Credential-Pro/1435067?space=21&entry=myfeedback
