### ISSUE TITLE
dotnet restore --interactive broken

### ISSUE THREAD

**Issue by marcpopMSFT** [microsoft/artifacts-credprovider#245]
---
**Issue moved from dotnet/sdk#16930**
- Please respond to @dustinmoris.

---

_From @dustinmoris on Thursday, April 15, 2021 7:30:28 AM_

How to test anger management of your developers:

1. Use Azure DevOps
2. Use NuGet feed from Azure DevPoops
3. Enable password expiry for users
4. Add NuGet package from private Azure DevPoops feed
5. User has to authenticate via `dotnet restore --interactive`
6. Works for a while until password expires
7. Now `dotnet restore` fails with a `401`
8. User tries to run `dotnet restore --interactive` again but instead of initiating auth process keeps getting `401`
9. User gets angry and punches a hole into the wall
10. User comes to GitHub and files issue with the hope that all of this bullshit will work for once in a while

**Comment by marcpopMSFT** [comment]
---
**Issue moved from dotnet/sdk#16930**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Thursday, April 15, 2021 7:30:32 AM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by brandorf** [comment]
We appear to be affected by this exact issue as well.  --interactive doesn't prompt at all.
