### ISSUE TITLE
using VSS_NUGET_EXTERNAL_FEED_ENDPOINTS on App Center

### ISSUE THREAD

**Issue by eman1986** [microsoft/artifacts-credprovider#248]
I'm looking to use Azure DevOps for nuget hosting and for our mobile app, we use Microsoft App Center for the mobile app and we'd like to use the build feature of App Center but setting VSS_NUGET_EXTERNAL_FEED_ENDPOINTS doesn't seem to work, I get the following error when I build:

> Please provide credentials for: https://pkgs.dev.azure.com/[company]/[group]/_packaging/PrivateNuGet/nuget/v3/index.json
UserName: Password: Unable to load the service index for source https://pkgs.dev.azure.com/[company]/[group]/_packaging/PrivateNuGet/nuget/v3/index.json.
  Response status code does not indicate success: 401 (Unauthorized).

I obviously have zero control on how the build system is built, but from what I read that's where the environment variable comes in for build systems.

This is what VSS_NUGET_EXTERNAL_FEED_ENDPOINTS is set up like in App Center:

`{"endpointCredentials": [{"endpoint":"https://pkgs.dev.azure.com/[company]/[group]/_packaging/PrivateNuGet/nuget/v3/index.json", "password":"MY_PAT"}]}`

**Comment by eman1986** [comment]
I contacted App Center and got the answer I needed.

**Comment by MaxDionysiusEm** [comment]
@eman1986 Could you please provide any information on how you solved this? Or what answer you got? thanks

**Comment by eman1986** [comment]
App center told me to create a nuget config file to connect to the nuget server and setup variables for the token. It's not what I'd like to do but it works so that's the important thing.

**Comment by MaxDionysiusEm** [comment]
So do you have the PAT credentials within the nuget config file? Or can the config file utilize github secrets?

**Comment by eman1986** [comment]
The pat is injected through a secret or build variable.

**Comment by MaxDionysiusEm** [comment]
Ok, so you have the configuration like
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="PrivateFeed" value="https://pkgs.dev.azure.com/XXX/_packaging/XXX/nuget/v3/index.json" />
  </packageSources>
</configuration>`

and inject the PAT to that path? 
Like 
` <PrivateFeed>
        <add key="Username" value="user" />
        <add key="ClearTextPassword" value="${{ secrets.PACKAGE_FEED_TOKEN }}" />
    </PrivateFeed>`

If not, could you please provide a sample for the YML config file?

**Comment by eman1986** [comment]
Yup just like that

**Comment by MaxDionysiusEm** [comment]
Unfortunately it still did not work for me.. Can't belive it's so difficult to simply build a .net core app in github actions and using a private azure artifacts feed for referenced nuget packages.. 

But thanks for your information. It's a good hint for me to search for more..

**Comment by eman1986** [comment]
Just curious did you add the config file to the folder where the sln file lives? If not that might be your problem.

**Comment by MaxDionysiusEm** [comment]
Yeah, the config file is right next to the sln file. 
I also tried a lot of combinations like

`dotnet restore src/Backend/solution.sln --configfile src/Backend/nuget.config`
or 
`dotnet restore src/Backend/solution.sln`
or directly pointing to the .csjproj (also with or without pointing to the config file)
`dotnet restore src/Backend/.../project.csproj`

**Comment by MaxDionysiusEm** [comment]
Ok, nevermind... Obviously I did not test one combination... 
I just removed the `--configfile ` flag and it did work... 
`dotnet restore src/Backend/solution.sln`

But I was required to directly write the PAT into the config file (for testing, of course)
So it now looks like
```
 <packageSourceCredentials>
    <PrivateFeed>
        <add key="Username" value="mail@someone.com" />
        <add key="ClearTextPassword" value="FEED_PAT" />
    </PrivateFeed>
</packageSourceCredentials>
```

When I tried it with the github secrets token, it resulted in an 401 unauthorized again:

```
 <packageSourceCredentials>
    <PrivateFeed>
        <add key="Username" value="mail@someone.com" />
        <add key="ClearTextPassword" value="${{ secrets.PACKAGE_FEED_TOKEN }}" />
    </PrivateFeed>
</packageSourceCredentials>
```

Is the token syntax maybe invalid?

**Comment by eman1986** [comment]
That could be it, glad you're making some progress.

**Comment by MaxDionysiusEm** [comment]
Finally I got it running. Just want to post it here, if anyone like me stumbles across this issue.

In our repo there's a `nuget.config` but without any credentials. There are just our sources inside. 
Next, in the GitHub action, I'm removing this private source from our `nuget.config` (it won't really remove it from the file, just from the cache or something, Idk) and add a new private feed with credentials. 

```
- name: Nuget remove
      run: dotnet nuget remove source {PrivateFeedName} --configfile src/nuget.config
      
    ## Add the private feed again but this time with credentials
    - name: Ensure GitHub NuGet Source
      run: |
        dotnet nuget add source https://pkgs.dev.azure.com/{Company}/_packaging/{FeedName}/nuget/v3/index.json \
          -n NewPrivateFeed \
          -u {UserName} \
          -p ${{ secrets.PACKAGE_FEED_TOKEN }} \
          --store-password-in-clear-text \
          --configfile src/nuget.config
    
```
The `PACKAGE_FEED_TOKEN` is the PAT for azure.
