### ISSUE TITLE
BUG: auth doesn't work with `dotnet list package --include-transitive --outdated`

### ISSUE THREAD

**Issue by StevenLiekens** [microsoft/artifacts-credprovider#279]
I have a package in a private registry which itself depends on another package in the same registry. I can successfully run `dotnet restore --interactive` and subsequently `dotnet restore` without interactive after installng this plugin.

The following however fails.

```
$ dotnet list package --outdated --include-transitive

The following sources were used:
   https://api.nuget.org/v3/index.json
   https://pkgs.dev.azure.com/redacted/_packaging/my-private-feed/nuget/v3/index.json

The given project `Redacted` has no updates given the current sources.
warn : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
error: Response status code does not indicate success: 401 (Unauthorized).
```

Running the same command with `--interactive` keeps endlessly prompting me to do a device code login, which tells me that the plugin is activated but doesn't work right.

**Comment by StevenLiekens** [comment]
Yea, you couldn't have just copied the issue for me? sheesh never mind then

**Comment by levimatheri** [comment]
@StevenLiekens were you able to resolve this? I'm experiencing the same issue.

**Comment by StevenLiekens** [comment]
No, I think I have to reopen the issue somewhere else but I really just can't be fucked to do it. Sorry.

**Comment by levimatheri** [comment]
@StevenLiekens LMAO okay. So frustrating!

**Comment by StevenLiekens** [comment]
Yeah I'm not sure why they don't just disable issues for this repository. Perhaps Microsoft likes to keep us around as their menagerie of great apes looking for a large enough stick to scratch our own back.

**Comment by sliekens** [comment]
@levimatheri I ran into even more issues that finally tipped the scale over. I figured my time is better spent ranting on the internet about shitty code than trying to make it work.

Behold, https://developercommunity.visualstudio.com/t/Azure-Artifacts-Credential-Provider-dele/10110841.
