### ISSUE TITLE
401 issues running dotnet.exe on Windows with Azure DevOps

### ISSUE THREAD

**Issue by robbaman** [microsoft/artifacts-credprovider#286]
Hi there!

We're running into problems using the dotnet.exe CLI in combination with an Azure DevOps feed. When using the CLI to add package references to a new project it will always result in a 401 with the advise to add `--interactive`:

```
info : Adding PackageReference for package 'Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore' into project 'C:\Workspaces\Project.csproj'.
info :   GET [URL]
warn : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
info :   Unauthorized [URL] 483ms
error: Response status code does not indicate success: 401 (Unauthorized).
```

When going through the requested steps it'll prompt a success message:

```
info : Adding PackageReference for package 'Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore' into project 'C:\Workspaces\Project.csproj'.
info :   GET [URL]
log  :     [CredentialProvider]DeviceFlow: [URL]
log  :     [CredentialProvider]ATTENTION: User interaction required. 
log  : 
log  :     **********************************************************************
log  : 
log  :     To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
log  : 
log  :     **********************************************************************
info :     [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'ADAL Device Code'
info :     [CredentialProvider]VstsCredentialProvider - Attempting to exchange the bearer token for an Azure DevOps session token.
info :   OK [URL] 908ms
info : Restoring packages for C:\Workspaces\Project.csproj...
info : Package 'Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore' is compatible with all the specified frameworks in project 'C:\Workspaces\Project.csproj'.
info : PackageReference for package 'Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore' version '6.0.1' added to file 'C:\Workspaces\Project.csproj'.
info : Committing restore...
info : Generating MSBuild file C:\Workspaces\Project.csproj.nuget.g.props.
info : Generating MSBuild file C:\Workspaces\Project.csproj.nuget.g.targets.
info : Writing assets file to disk. Path: C:\Workspaces\obj\project.assets.json
log  : Restored C:\Workspaces\Project.csproj (in 231 ms).
```

This is all very promising, however when immediately performing another `dotnet add package` command on the same solution to add another package, it'll error out with a 401 once again as though it never stored the credentials it received.

I haven't been able to find any information as to where the credentials are stored so I'm not sure how to clear old credentials (if any are present). I did ensure I installed the latest version of the Credentials Manager and removed all existing PATs from my Azure account, but to no avail.

We use a powershell script that creates a dozen or so projects with numerous package references to quickly generate new microservice solutions. To have to add `--interactive` behind every call to `dotnet add package` is not a very workable solution.

Any help or pointers would be greatly appreciated.

Thanks in advance.

**Comment by levimatheri** [comment]
@robbaman Were you able to resolve this? I'm experiencing same issue.

**Comment by robbaman** [comment]
@levimatheri not really. We ended up circumventing this issue by creating a PAT manually and locally modifying the NuGet.config on each developer machine by adding the username/PAT for the source. This makes the error go away, but I'm confused this is necessary.
