### ISSUE TITLE
Release `>= 0.1.28` breaks MSAL browser (web flow) support

### ISSUE THREAD

**Issue by kyle-rader** [microsoft/artifacts-credprovider#292]
We are still investigating but updating to release 0.1.28 AND Nuget 6.0.0 resulted in Nuget.exe auth no longer working on Mac, and I believe on Windows as well. (But [our auth CLI cred provider](https://aka.ms/azureauth) warms the shared cache on Windows so it was less impactful).

We will update this issue as we learn more.

**Comment by kyle-rader** [comment]
We have a reliable repro of this issue now. Using the netfx (net framework) cred provider, and running nuget under `mono64` on Mac OS (arm, m1 device) version 0.1.28 of the cred provider with nuget 5.10.0 or 6.0.0 fails to prompt using the web browser and leaves nuget to ask for username and password, which will never work for internal ADO feeds.

**Comment by jiaw37** [comment]
@kyle-rader is the repro in the recorded meeting? Are we able to use fiddler to do the repro there might be some insight on whether there is a failing network call?

**Comment by kyle-rader** [comment]
We did a follow up, I'll get you the recording internally. We did not go as far as looking at Fiddler since we reached about as far as we can prioritize understanding this. From what we can tell the only suspect change in the MSAL version going from `4.11` to `4.32.1`. The only code change in `0.1.28` release looks related to parsing the Vss Credentials JSON which isn't in use in our scenario.

**Comment by jiaw37** [comment]
Here are the steps to repro in an ubuntu environment, I am using version 20.04
Install mono version 6.12.0.122
Install the credProvider 0.1.28, BOTH netcore and netfx and place them in the plugin directory (.nuget/plugins)
Install Nuget 6.0 (shouldn't really matter which version)
Set env var `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED=true`, false ends up using the device login flow

Run `mono nuget.exe install <NameofPackage> -Version <version> -Source <Connect-To-Feed-SourceURL>  -nocache -directdownload`

The result of running the above command will prompt the user for `Please provide credentials for: <SomeUrl> \n UserName: `

The expected result should be a pop up of a Microsoft login browser prompt in a new window.
You can see this when you revert credProvider to 0.1.25, move the plugins to .nuget/plugins directory, and run the command again.

**Comment by akshita31** [comment]
I am able to repro this on Windows11 as well with the latest version

**Comment by jiaw37** [comment]
@akshita31 just to check, you have the env var `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED` set to `true` correct?
It looks like it is happening for dotnet as well and not just NuGet.

**Comment by akshita31** [comment]
> @akshita31 just to check, you have the env var `NUGET_CREDENTIALPROVIDER_MSAL_ENABLED` set to `true` correct? It looks like it is happening for dotnet as well and not just NuGet.

No I dont have this environment variable set.
![image](https://user-images.githubusercontent.com/12554141/152461072-f2ed08aa-fc5c-4461-9619-a62e074af128.png)

**Comment by kyle-rader** [comment]
Just confirmed that with version 1.0.0 the cred provider still skips Web Auth and only does device code flow.

**Comment by johnterickson** [comment]
When directly and indirectly invoking the cred provider, Windows seems to work:
```
D:\nuget\6.1.0>"%HOMEDRIVE%%HOMEPATH%\.nuget\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe" -U https://pkgs.dev.azure.com/mseng/_packaging/Codex-Deps/nuget/v3/index.json -V Debug
[Verbose] [CredentialProvider]Running in stand-alone mode
[Verbose] [CredentialProvider]Command-line v1.0.0+94af8126cf520805dd7e213b92cdecd9d8728d1f: "C:\Users\jerick\.nuget\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe"  -U https://pkgs.dev.azure.com/mseng/_packaging/Codex-Deps/nuget/v3/index.json -V Debug
...
[Minimal] [CredentialProvider]ATTENTION: User interaction required.

    **********************************************************************

    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ******* to authenticate.

    **********************************************************************

[Information] [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'Msal Device Code'
```

```
D:\nuget\6.1.0>nuget list -Source https://pkgs.dev.azure.com/mseng/_packaging/Codex-Deps/nuget/v3/index.json
MSBuild auto-detection: using msbuild version '17.1.0.7609' from 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin'.
    [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'Msal UI'
```

Also seems to work in Ubuntu with `dotnet` 6.0.201:
john@jerick-hpz440:/mnt/d/C_JUNCTIONS/.nuget/packages/microsoft.sbomcore/2.0.99$ dotnet nuget push --interactive -s https://pkgs.dev
    [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/jerickmsft/PrivateProject/_packaging/2022_03_30/nuget/v3/index.json  
    [CredentialProvider]ATTENTION: User interaction required.                                                                       
                                                                                                                                    
    **********************************************************************                                                          
                                                                                                                                    
    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FWKMRP63G to authenticate.  
                                                                                                                                    
    **********************************************************************                                                          
    [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'Msal Device Code'

**Comment by MeikelLP** [comment]
Hi,
I don't know if this is the same bug but we try to install our powershell modules (published to Azure Artificats) and the `Install-Module` (or `Register-PSRepository`) command triggers the credential provider.
Sadly the credential provider fails (400 BadRequest) and loops us in the device login phase. I successfully authenticated via Device login but after that I get another device login (and so on).

Is this an issue of the credential provider or powershell (what repo/product exactly?)

Normal dotnet/nuget commands work fine (Windows 10).

**Comment by DanielTheCoder** [comment]
Today I run into the same problem, seems like we are not alone with this issue, it's also tracked here: https://github.com/dotnet/sdk/issues/22987

Seems like a workaround to get device code flow information for `dotnet tool` is to run like this `dotnet tool update -g <nuget_name> --interactive --verbosity minimal`

**Comment by MeikelLP** [comment]
@Ellestad1995 nope. no solution to this date

**Comment by JohnSchmeichel** [comment]
Trying to tease apart these issues, may need to create separate ones if folks are still have issues here. But want to address a few items to see if it unblocks anyone:

#### Old versions
If using anything less than 1.0.0 (as of this writing 1.0.2 is the latest) version please try your scenario again with the latest version installed. There have been many changes to dependencies and platform fixes that may have resolved some of these early issues.

#### No system browser prompt
If your not seeing the system browser or account picker prompt and using the .NET Core 3.1 or .NET 6.0 versions this is a known limitation in NuGet for .NET Core plugins. Per the credential provider spec for [cross-platform plugins ](https://learn.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin#creating-a-cross-platform-authentication-plugin) the CanShowDialog flag is always specified as false. This means the system browser or account picker is never used and device code is used if interactive authentication is allowed.

To workaround this you can set the following environment variable to override this behavior:
```bash
# cmd
set NUGET_CREDENTIALPROVIDER_FORCE_CANSHOWDIALOG_TO=true

# bash
export NUGET_CREDENTIALPROVIDER_FORCE_CANSHOWDIALOG_TO=true
```
We're following up with the NuGet team to change this behavior. Somewhat related to these are the various dotnet CLI issues linked that effectively hide the device code output by turning down the logging.

#### PowerShell repeated prompts
Uncertain what's happening here but the description of the repro indicates either an issue getting a valid token, or an issue retrieving a cached credential. The PowerShell usage of the credential provider will first run it to initiate device flow, and then run it again immediately after (and possibly twice for any command that requires it) expecting cached credentials to work to print out a token. If there's an issue caching the credentials from device flow or an issue exchanging for a session token then it will always prompt.

If you still have a repro of this please ensure the following:
1. You have the latest version of the credential providers installed
2. Run ```set NUGET_CREDENTIALPROVIDER_MSAL_ENABLED=true```
3. Run ```set NUGET_CREDENTIALPROVIDER_LOG_PATH=%USERPROFILE%\artifacts-credprovider.log```

Run Install-Module ... of your repro and provide the logs. **Note**: the logs may contain access tokens and other personal data, so please scrub these before posting.

**Comment by JohnSchmeichel** [comment]
Closing this, please open new issues if your still experiencing any problems here.
