### ISSUE TITLE
installcredprovider.sh: download fails, wrong url generated

### ISSUE THREAD

**Issue by mlankamp** [microsoft/artifacts-credprovider#303]
The latest version of the script fails because the tag version is set to latest, this will create the following url: 
```https://github.com/Microsoft/artifacts-credprovider/releases/download/latest/Microsoft.NuGet.CredentialProvider.tar.gz```

the url should be:

```https://github.com/Microsoft/artifacts-credprovider/releases/download/latest/Microsoft.NuGet.CredentialProvider.tar.gz```

the order of the words latest and download is wrong

**Comment by mlankamp** [comment]
@satbai: the error comes from this line https://github.com/microsoft/artifacts-credprovider/blob/5775dd7f0408fdf624f380959efb205c37d347fb/helpers/installcredprovider.sh#L34

**Comment by NArnott** [comment]
Just noticed this too. I commented on the PR that seems to have done this. https://github.com/microsoft/artifacts-credprovider/pull/302#issuecomment-1061157356

**Comment by sethcrichton** [comment]
The issue that I am seeing is that the "latest" location is not available.  
https://github.com/Microsoft/artifacts-credprovider/releases/download/**latest**/Microsoft.NuGet.CredentialProvider.tar.gz

I can get to the file via the direct version link
https://github.com/Microsoft/artifacts-credprovider/releases/download/**v1.0.0**/Microsoft.NuGet.CredentialProvider.tar.gz

**Comment by NArnott** [comment]
Latest still works: https://github.com/Microsoft/artifacts-credprovider/releases/latest/download/Microsoft.NuGet.CredentialProvider.tar.gz

It's because they flipped /latest and /download.

**Comment by mlankamp** [comment]
Current workaround in my docker file is to add the following line:
```
ENV AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION v1.0.0
```

**Comment by brandonavant** [comment]
My team an I are observing this problem as well. Hopefully we can get an ETA on a fix soon? We're trying to avoid changing Docker files for multiple microservices running pipelines, knowing that a fix is probably soon to arrive.

**Comment by tareks** [comment]
It also appears that this filename does not match the one published for .net6 in the latest release (whether the version is supplied or not)?

https://github.com/microsoft/artifacts-credprovider/blob/5775dd7f0408fdf624f380959efb205c37d347fb/helpers/installcredprovider.sh#L20

Referenced filename: `Microsoft.Net6.CredentialProvider.tar.gz`
Actual release asset name: `Microsoft.Net6.NuGet.CredentialProvider.tar.gz`

Release URL at the time:
https://github.com/microsoft/artifacts-credprovider/releases/download/v1.0.0/Microsoft.Net6.NuGet.CredentialProvider.tar.gz

**Comment by DrEsteban** [comment]
+1 to all these issues as well

It's possible Microsoft still has some release pipelines running that will eventually place the expected files in the expected locations, but this is definitely an inexcusable release blunder that Microsoft needs to triage.

**Comment by phil-hodgson** [comment]
We've reverted the changes. Apologies for the interruption. Please reopen this issue if the revert has not resolved the issue on your end.

**Comment by DrEsteban** [comment]
Can confirm - issue appears resolved

**Comment by brandonavant** [comment]
> Can confirm - issue appears resolved

Same. The issue appears to be resolved with the revert.
