### ISSUE TITLE
 The artifacts-credprovider dosnt work with arm64 architecture.

### ISSUE THREAD

**Issue by klaudiuszstawski** [microsoft/artifacts-credprovider#328]
I am deploying docker images to different architectures using  **docker buildx** 
When I build an image the tool can not start with Linux/arm64 architecture

 _/usr/share/dotnet/sdk/6.0.302/NuGet.targets(130,5): error : Problem starting the plugin '/root/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll'. Plugin 'CredentialProvider.Microsoft' failed within 7.798 seconds with exit code ._

It seems that the tool is not published for linux/arm64

Sample script which try to build image for arm
 docker run --privileged --rm tonistiigi/binfmt --install arm64
            docker run --privileged --rm tonistiigi/binfmt
            docker buildx create --use
            docker buildx build --build-arg FEED_URL=$(NugetUrl) --build-arg PAT=$(READNUGETPACKAGESPAT)  --platform linux/arm64 \
                -f 'src/Edge/Dockerfile' \
                -t $(EdgeContainerRegistry):$(build.buildNumber) \
                -t $(EdgeContainerRegistry):latest \
                --push \
                'src/Edge'

**Comment by Madnax1337** [comment]
@klaudiuszstawski Have you solved the issue? I am facing the same one and have absolutely no idea what is causing the credential provider plugin to fail for arm architecture.

**Comment by Agular** [comment]
I have the same issue.

**Comment by henioStraszny** [comment]
I've had the same issue, in fact it has nothing to do with Credentials Helper, most likely your container build kit does not support arm64, and you are building using arm64 image which your builder cannot run.

You can check it using:

`docker buildx ls`

I've rsolved that issue using executing:

`docker run --privileged --rm tonistiigi/binfmt --install all`

I've found that here:
https://docs.docker.com/build/building/multi-platform/#cross-compilation
