### ISSUE TITLE
IsRetry is toggled on for the initial attempt to search a secondary package source

### ISSUE THREAD

**Issue by sliekens** [microsoft/artifacts-credprovider#329]
This is a continuation of a discussion on the feedback forum: https://developercommunity.visualstudio.com/t/Azure-Artifacts-Credential-Provider-dele/10110841?viewtype=all

There is code somewhere in the plugin that sets IsRetry=True when a nuget package is not found on one feed, and there is another feed that can be tried. This causes problems during package searches when a nuget.config file contains multiple feeds, e.g. a public and a private feed.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
    <add key="private" value="https://pkgs.dev.azure.com/private/_packaging/private-nuget-feed/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

The behavior I'm seeing when searching a private package is roughly as follows

``` sh
$ dotnet package add SomePrivatePackage # version not specified so it will search all feeds
```

1. the (dotnet) nuget client searches nuget.org
2. nuget.org responds with 404 Not Found
3. the (dotnet) nuget client searches my private feed
4. the credprovider is invoked with the IsRetry=True bit and **clears my session token cache by design** https://github.com/microsoft/artifacts-credprovider/blob/cdc427e8236212b33041b4276961855b39bbe98d/CredentialProvider.Microsoft/RequestHandlers/GetAuthenticationCredentialsRequestHandler.cs#L144-L149
6. my private feed responds with 401 Unauthorized

It is my conclusion that the IsRetry bit is toggled on when it shouldn't be. A NotFound error should not result in my token cache being cleared.

My suggested fix is to change the error handling code to only clear the session token cache when an authorization error is observed.

**Comment by sliekens** [comment]
https://developercommunity.visualstudio.com/t/Azure-Credprovider:-IsRetry-is-toggled-T/10125533

**Comment by tboby** [comment]
@johnterickson Could you possibly have a look at the issue workflow is supposed to be for problems like this? This is firmly a code error in this repo, which makes Azure Artifacts unusable in certain situations.

This issue has been sent to Developer Community, where it has been assessed and closed as out of the scope.

https://developercommunity.visualstudio.com/t/Azure-Credprovider:-IsRetry-is-toggled-T/10125533

https://developercommunity.visualstudio.com/t/Azure-Artifacts-Credential-Provider-dele/10110841?viewtype=all

**Comment by johnterickson** [comment]
A few quick thoughts:
1. Don't have more than one package source in your nuget.config. It makes you insecure: https://devblogs.microsoft.com/devops/changes-to-azure-artifact-upstream-behavior/
2. It sounds like NuGet/dotnet is incorrectly calling the cred provider with -IsRetry. If that is correct, report at https://github.com/NuGet/Home. Deleting the session token is our side of the contract AFAICT.
3. Session tokens are supposed to be super transient. The question is why is your ADAL/MSAL token not working. Try using the env var to opt in to MSAL mode. It's newer and we're working on making that default.
4. If you are on WSL, you can try https://github.com/johnterickson/CredentialProvider.Redirect but that's a side project FWIW.

**Comment by sliekens** [comment]
Okay I think this discussion should be moved to NuGet if they are the ones setting the IsRetry flag. Hopefully someone can move using a GH tool? 😀

> Session tokens are supposed to be super transient. The question is why is your ADAL/MSAL token not working. Try using the env var to opt in to MSAL mode. It's newer and we're working on making that default.

What do you mean by ADAL/MSAL token? I'm not using single sign-on but instead a device code login flow. I'm not sure about the statement that the token is supposed to be super transient. I certainly don't want to be doing device code logins every time I need to run a nuget command.

> If you are on WSL, you can try https://github.com/johnterickson/CredentialProvider.Redirect but that's a side project FWIW.

I'll check it out when I have a moment. I'm using the credprovider in a dev container backed by Docker on WSL2.

**Comment by johnterickson** [comment]
@sliekens Can you take a look at https://github.com/NuGet/Home/issues/11210 ?

W.r.t. MSAL & cache https://github.com/microsoft/artifacts-credprovider/blob/master/CredentialProvider.Microsoft/Util/EnvUtil.cs :
NUGET_CREDENTIALPROVIDER_MSAL_ENABLED
NUGET_CREDENTIALPROVIDER_MSAL_FILECACHE_ENABLED
NUGET_CREDENTIALPROVIDER_MSAL_FILECACHE_LOCATION

**Comment by sliekens** [comment]
@johnterickson thanks again but ADAL/MSAL token caching on disk is only supported on Windows(?) if I'm not reading this code wrong

https://github.com/microsoft/artifacts-credprovider/blob/cdc427e8236212b33041b4276961855b39bbe98d/CredentialProvider.Microsoft/CredentialProviders/Vsts/AdalTokenCacheUtils.cs#L16-L20

https://github.com/microsoft/artifacts-credprovider/blob/cdc427e8236212b33041b4276961855b39bbe98d/CredentialProvider.Microsoft/CredentialProviders/Vsts/MSAL/MsalTokenProvider.cs#L40-L55

**Comment by johnterickson** [comment]
Ugh why does MSAL make this so hard... Filed https://github.com/microsoft/artifacts-credprovider/issues/345

**Comment by johnterickson** [comment]
There's a number of "gotchas" in this thread, but I do want to reiterate that the reason developers inside Microsoft don't hit these problems is because we've pushed really hard on getting all teams to only have one source in their `nuget.config`.  Not `nuget.org'/`npmjs.com` and one Artifacts feed - exactly one source in the `nuget.config`.  

Here's the security whitepaper that's a better description than the link I gave previously: https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/

**Comment by sliekens** [comment]
I won't argue with the benefits of using a single aggregate feed with added protection against private package substitution attacks, but I found it not worth the drawback. It breaks things like `dotnet list package --outdated` exactly because upstream sources are not included in the search. I much prefer to have 2 package sources and use a packages.lock.json file for checking the integrity of the binaries.

I look forward to seeing MSAL implemented for Unix-like platforms. 😀

**Comment by tboby** [comment]
While I understand that; having this workflow fail is really confusing, and that Azure Artifacts expects best practice that isn't really documented in .NET docs nor NuGet docs is difficult.

https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources
```
<packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Contoso" value="https://contoso.com/packages/" />
    <add key="Test Source" value="c:\packages" />
</packageSources>
```

https://docs.microsoft.com/en-us/nuget/hosting-packages/overview
> Regardless of how packages are hosted, you access them by adding them to the list of available sources in NuGet.Config.

Azure artifacts docs/"Connect to feed" guide hint at it by clearing, but doesn't explain that it's a requirement:

https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-setup?view=azure-devops

In some places it appears to guide you towards simply adding the source

https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops&tabs=windows#publish-nuget-packages

It also seems that upstream sources aren't supported for all feed types?

https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops#best-practices-feed-ownerspackage-publishers

Worst of all, it appears that using an upstream source has a sudden and permanent cost? My nuget cache folder locally is 14GB.

> Once you've enabled an upstream source, every time you install a package from the public registry, Azure Artifacts will save a copy of that package in your feed.


Perhaps more importantly though, consider the process that somebody considering adopting Azure Artifacts as a private package registry might be taking:

First they will learn how to build packages using `dotnet pack`, and likely will use a local feed to experiment with how multiple sources works.

Then they'll create an Azure Artifacts project, add it as a source, then push it. Then they might experiment with how to use it to pull that package back down with different permissions levels. They might then experiment with using their new feed via their CI/CD, or through a clean environment like a docker container. Any of this could randomly fail unless they on upstream sources.

I don't think it's reasonable to expect somebody evaluating the core of the service (A private package repository) to commit to using a complicated feature (upstream sources) which has additional costs.

**Comment by johnterickson** [comment]
@sliekens `outdated` should work: 
![image](https://user-images.githubusercontent.com/10488772/189975189-87b49c1a-6697-4d32-9928-1f436a149073.png)
Thinking again, it may be dependent on a feature that we just rolled out or are currently rolling out, so perhaps it's not out everywhere.

@tboby No argument that there are some broken and/or painful aspects of upstreams and onboarding. I will forward your feedback to the NuGet and Artifacts PM teams.

FWIW we are rolling out support for "some upstreams for public feeds" - for example the feed for this repo.

If upstreams is not the right match for your needs, the option for securely mixing private packages and public package usage on `nuget` specifically is to leverage package source pinning: https://devblogs.microsoft.com/nuget/quickly-map-your-nuget-packages-to-sources/

**Comment by kartheekp-ms** [comment]
@sliekens - The actual issue reported in this issue should be fixed in https://github.com/NuGet/NuGet.Client/pull/4794

**Comment by ransagy** [comment]
@kartheekp-ms @johnterickson sorry for the direct pings, but -

I believe i hit the same thing (or a very similar issue) in #347 (which is now clearly mislabled now that i understand the scenario) which does not (directly) use dotnet list subcommands.
Is this related? If so, since the fix seems to have been very specific, what and where do i open an issue on this?
As this involves so many different repos/parts im quite confused on that at this point.
