### ISSUE TITLE
Running CredentialProvider.Microsoft.exe gives error "did not have a valid embedded signature"

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/artifacts-credprovider#330]
I'm using https://aka.ms/install-artifacts-credprovider.ps1 to install the netcore version of the cred provider and every time i run it under dotnet restore, i'm getting the error "did not have a valid embedded signature" for CredentialProvider.Microsoft.exe.

**Comment by pieandcakes** [comment]
I noticed that the .exe isn't signed but the .dll is. Is there a reason why there is an unsigned .exe and are we supposed to set `NUGET_NETCORE_PLUGIN_PATHS` to the .exe or the .dll?

**Comment by ofmmmmm5** [comment]
I got same issue as well. This seems to be not transient. Can we have someone take a look at this ticket?

**Comment by ofmmmmm5** [comment]
@pieandcakes Any luck on workaround this issue?

**Comment by pieandcakes** [comment]
@ofmmmmm5 I ended up setting `NUGET_NETCORE_PLUGIN_PATH` directly to the path of `CredentialProvider.Microsoft.dll` and it seems to have worked.

**Comment by fabricioferreira** [comment]
https://developercommunity.visualstudio.com/t/Artifacts-CredProvider-for-NetCore-is-no/10337807
