### ISSUE TITLE
Session token cache is invalidated before its due time

### ISSUE THREAD

**Issue by sliekens** [microsoft/artifacts-credprovider#343]
Hi, this is the third time I try to report this but my issue keeps getting closed by a bot. So this time I'm tagging the top 10 contributors here for visibility. Please mark this as a Bug so it doesn't get closed. @satbai @aldoms @jmyersmsft @AlexVTor @zarenner @johnterickson @jiadji aw37 @crmann1 @jotaylo @keithrob —sorry for the inbox spam. 😏

---

There is error handling code in the plugin that invalidates access tokens in the SessionTokenCache.dat file when an error is observed.

https://github.com/microsoft/artifacts-credprovider/blob/cdc427e8236212b33041b4276961855b39bbe98d/CredentialProvider.Microsoft/RequestHandlers/GetAuthenticationCredentialsRequestHandler.cs#L144-L149

This code is problematic because it is executed for **any** error, not just authorization errors.  
An example could be doing `dotnet add package Xyz` where _Xyz_ doesn't exist. The result is a Not Found error which then invalidates the token cache because of the lines above.

**Comment by jmyersmsft** [comment]
That would be a bug in NuGet, not artifacts-credprovider. The intent of the IsRetry flag is to tell the credential provider that the previously retrieved credential didn't work, so artifacts-credprovider is doing the right thing by discarding the cached credential and fetching a new one.

NuGet takes bugs at https://github.com/NuGet/Home/issues
