### ISSUE TITLE
Default configuration forces extra unnecessary password prompts

### ISSUE THREAD

**Issue by will-bartlett** [microsoft/artifacts-credprovider#350]
The default token provider for ADO is AdalTokenProvider.cs. This provider has code `var parameters = new PlatformParameters(PromptBehavior.Always);` . The documentation behavior of this value is "The user will be prompted for credentials even if there is a token that meets the requirements already in the cache." This prompt behavior is almost certainly not the desired prompt behavior. From the [documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.promptbehavior?view=azure-dotnet), there are five possible behaviors - `Always`, `Auto`, `Never`, `RefreshSession`, and `SelectAccount`. The desired behavior is either `Auto` ("Acquire token will prompt the user for credentials only when necessary. If a token that meets the requirements is already cached then the user will not be prompted.") or `SelectAccount` ("Prompt the user to select a user account even if there is a token that meets the requirements already in the cache. This enables an user who has multiple accounts at the Authorization Server to select amongst the multiple accounts that they might have current sessions for.").

The ADAL SDK is also long not-recommended by Microsoft Identity, but, for whatever reason, still the default. The MSAL SDK (which Microsoft Identity recommends) is not the default, but is implemented in MsalTokenProvider.cs. This token provider already has a better behavior - `msalBuilder.WithPrompt(Prompt.SelectAccount);`.

Importantly, while PromptBehavior.Always / Prompt.Login and PromptBehavior.SelectAccount / Prompt.SelectAccount are similar in that they both require that UX be shown, they differ in what type of UX is shown. PromptBehavior.Always and Prompt.Login show a username prompt, followed by a prompt for the user's default credential (e.g. password), even if the user is getting single sign-on (SSO) from the operating system or web view. PromptBehavior.SelectAccount / Prompt.SelectAccount take advantage of the operating system's SSO and show a user selection prompt (which is better than retyping the username). Further, after selecting the user, with the SelectAccount prompt behavior, the user is not required to type any credential at all if the user has SSO from the operating system or web view.

**Comment by will-bartlett** [comment]
Please either change the default to MSAL or fix the ADAL token provider to not require extra prompts (or both).

**Comment by johnterickson** [comment]
We are moving to MSAL once we get the broker figured out and tested. cc @JohnSchmeichel
