### ISSUE TITLE
Plugin assemblies are not digitally signed

### ISSUE THREAD

**Issue by FabrizioSalis** [microsoft/artifacts-credprovider#372]
Hi, I installed the credential provider to use my private feeds with the nuget tool. 
The plugin was **not working**, because it was not digitally signed (more in details, the login prompt was not showing up).

As a workaround, I signed the **CredentialProvider.Microsoft.exe** it using my company's certificate and then everything started to work, a login was popping up and eventually I downloaded my nupkg files. 

Can you please sign the assemblies?

**Comment by fabricioferreira** [comment]
https://developercommunity.visualstudio.com/t/Artifacts-CredProvider-for-NetCore-is-no/10337807
