### ISSUE TITLE
Issue with installcredprovider.sh inside docker

### ISSUE THREAD

**Issue by Ich1goSan** [microsoft/artifacts-credprovider#377]
Hi, recently my team faced an issue with building images using sdk:3.1 after last merged [PR](https://github.com/microsoft/artifacts-credprovider/commit/144f57b3159aaa34cfeace7c4b8e9aca81df240f). (we use artifacts from Azure DevOps)
Currently, we are unable to move to .net 6 images. (we know that support for 3.1 is end of support)
Our dockerfile starts with
```
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build

ARG FEED_ACCESSTOKEN

RUN wget -O - https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | bash
ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true

ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS "{\"endpointCredentials\": [{\"endpoint\":\"https://pkgs.dev.azure.com/thereachagency/AtriboCloud/_packaging/cloud_feed/nuget/v3/index.json\", \"username\":\"docker\", \"password\":\"${FEED_ACCESSTOKEN}\"}]}"

... other stuff like copy, build ,publish
```

Because installcredprovider.sh in master recently updated to use .net 6 we are unable to build a docker image, after dotnet restore we face the error:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
  - The following frameworks were found:
      3.1.32 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

```
So my question is are we safe to use previous versions of installcredprovider.sh like [release-1.0.2](https://github.com/microsoft/artifacts-credprovider/blob/c2bc059db245a21f09d4e9afa92bba813c567488/helpers/installcredprovider.sh)?
Or maybe you may suggest other options? I guess not only our team face this problem after that change

**Comment by Janaza** [comment]
Had the same issue when trying to build a .net 5 image. Downgrading to version v1.0.1 resolved our issue:
```https://raw.githubusercontent.com/microsoft/artifacts-credprovider/v1.0.1/helpers/installcredprovider.sh | bash```

**Comment by TheTerrasque** [comment]
Hit with the same issue. [The PR](https://github.com/microsoft/artifacts-credprovider/pull/375) does have a workaround mentioned: 

    curl -fsSL https://aka.ms/install-artifacts-credprovider.sh | USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER=false bash

**Comment by shessane** [comment]
Hi, same here. I think it's a very bad idea to make breaking changes like this. Even if netcore 2 or 3 are now deprecated, the script is part of a DockerFile that is versionned. So now we need to update legacy images to do the fix.
You could have just keep the version 1.x for the old .Net, and upgrade to a version 2.x.
Or you can change the URL https://aka.ms/install-artifacts-credprovider.sh to some https://aka.ms/install-artifacts-credprovider-net6.sh

**Comment by LewdinAc** [comment]
I presented the same issue and solved this one with @TheTerrasque comment, but instead of putting the variable in the curl command, we put it some lines above as: ENV USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER=false

**Comment by clbarrett** [comment]
I am an affected user as well.  Am attempting the ENV solution from LewdinAc.  Will report back if it succeeds.

**Comment by clbarrett** [comment]
The ENV USE... worked for me with no other changes (version or otherwise).  Thanks for the workaround.  Was really sweating bullets trying to figure out what broke.
