### ISSUE TITLE
Installscript updates break existing pipelines without notice

### ISSUE THREAD

**Issue by rik-v** [microsoft/artifacts-credprovider#378]
## What
The updates to the install scripts from last weeks Tuesday (which was March 28th, 2023, at the time of writing), break existing pipelines without notice.

## Why
The reason for this: the default was switched from netcore3.1 to .net6.  
The effect this has, is that "default" uses of the cred. provider install scripts result in non-working builds now for .net versions older than 6.0
Which makes perfect sense from a .net versioning point of view, however, it isn't mentioned anywhere in release/change-notes.

A lot of people are likely using the default example on how to use the credential provider, which simply pulls the latest install scripts. Those scripts will now break builds that aren't running .net6 or higher.
And yes, I'm well aware that older versions are out-of-support, but still, it'd be very helpful if there'd at least be a changelog on this breaking change 😃 

## Requested change
Document the (to some: breaking) change in the release/change-notes.
Perhaps it's an idea to add a part to the main readme detailing this change too? (like was done for v1.0.0)

## Workaround/Fix
set the `USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER` to false, so for those running into this issue with Docker, add this before the install layer:
```
ENV USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER false
```

**Comment by mnegahi** [comment]
no idea why you guys have decided to apply breaking change without any warning.

**Comment by JohnSchmeichel** [comment]
Apologies for pulling the rug from under you here. Unfortunately, script updates are instant and not part of the latest release, we'll do a better job communicating these changes in the future.

As mentioned the workaround is to explicitly ask for the .NET Core 3.1 version. We plan on pulling that out completely, but will announce that before those changes go in.
