### ISSUE TITLE
Add installation method using `winget`

### ISSUE THREAD

**Issue by asilverman** [microsoft/artifacts-credprovider#379]
## Overview
The winget command line tool enables users to discover, install, upgrade, remove and configure applications on Windows 10 and Windows 11 computers. This tool is the client interface to the Windows Package Manager service. (For more information [see here](https://learn.microsoft.com/en-us/windows/package-manager/winget/)

Currently the process of installing & updating [artifacts-credprovider](https://github.com/microsoft/artifacts-credprovider) is a bit challenging and requires active user interaction. Using winget to install and update would be a much nicer and easier experience and would allow users to benefit from using the latest version with the latest fixes.

To add [artifacts-credprovider](https://github.com/microsoft/artifacts-credprovider) to winget is simple, just add to CI/CD pipeline a task per [the following documentation](https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline). If you need more information you can also contact @denelon for help

## Benefits

Often times  [artifacts-credprovider](https://github.com/microsoft/artifacts-credprovider) is one of the dev setup dependencies and having an easy way to winget it would make it easier to onboard and ensure that developers can spin a dev environment quickly

**Comment by denelon** [comment]
I think the main challenge currently is the release artifacts are NuGet packages rather than an "installer" or a "portable" application.

**Comment by cataggar** [comment]
Yes, it would be great to simplify dev setup. Currently, we have developers install the SDK with:
``` ps1
winget install -e --id Microsoft.DotNet.SDK.6 -v 6.0.403
```

It would be great if we could do something similar to:
``` ps1
winget install --id Microsoft.ArtifactsCredProvider
```
 
This would save a lot of developer time.

**Comment by ShadowXVII** [comment]
The team are extremely ruthless with closing tickets without upvotes. I'd highly recommend upvoting & commenting on 

https://developercommunity.visualstudio.com/t/Add-Windows-installer-options-for-Azure/10308779

so we actually get some traction on alternate deployment options.
