### ISSUE TITLE
RateLimiting when using https://aka.ms/install-artifacts-credprovider.ps1 

### ISSUE THREAD

**Issue by Hylaean** [microsoft/artifacts-credprovider#380]
We're using install-artifacts-credprovider on Azure Devops hosted agents as it is not practical using NuGetAuthenticate@1 task in our pipeline.

The issue we're having comes from reaching github rate limits very often leading to failed builds using this method. I was wondering if you had in your plans to switch to another host for the binaries?

**Comment by JohnSchmeichel** [comment]
No plans on changing the hosting. Why is using NuGetAuthenticate@1 not practical? It includes a copy of this credential provider and is better suited for downloads at scale.
