### ISSUE TITLE
CredentialProvider.Microsoft.exe is not signed

### ISSUE THREAD

**Issue by danr-stadion** [microsoft/artifacts-credprovider#387]
When trying to use the credential provider in Rider, I get an error that the CredentialProvider.Microsoft.exe is not signed:

```
The plugin at 'C:\Users\xxx\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe' did not have a valid embedded signature.
Exception while querying credential providers for: https://pkgs.dev.azure.com/xxx/_packaging/xxx/nuget/v3/index.json
NuGet.Credentials.PluginException: The plugin at 'C:\Users\xxx\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe' did not have a valid embedded signature.
   at NuGet.Credentials.SecurePluginCredentialProvider.GetAsync(Uri uri, IWebProxy proxy, CredentialRequestType type, String message, Boolean isRetry, Boolean nonInteractive, CancellationToken cancellationToken)
   at JetBrains.Rider.Backend.Features.NuGet.CredentialProvider.RiderNuGetCredentialService.GetCredentialsAsync(Uri uri, IWebProxy proxy, CredentialRequestType type, String message, CancellationToken cancellationToken)
```

Would it be possible to get this signed when included in the downloadable ZIP?

Thanks,
Dan.

**Comment by JohnSchmeichel** [comment]
Yes, we'll ship an update to have this signed. For .NET Core the CredentialProvider.Microsoft.dll binary is signed, as normally NuGet will invoke that provider via ```dotnet CredentialProvider.Microsoft.dll```, and for the .NET Framework CredentialProvider.Microsoft.exe is signed as the executable is used directly there.

Are you setting ```NUGET_NETFX_PLUGIN_PATHS```, ```NUGET_PLUGIN_PATHS```, or ```NUGET_CREDENTIALPROVIDERS_PATH``` at all? Curious how the .exe version is being picked up from the netcore plugin directory.

**Comment by danr-stadion** [comment]
> Are you setting `NUGET_NETFX_PLUGIN_PATHS`, `NUGET_PLUGIN_PATHS`, or `NUGET_CREDENTIALPROVIDERS_PATH` at all? Curious how the .exe version is being picked up from the netcore plugin directory.

I haven't explicitly set any of those environment variables, so I'm not sure how Rider determines what to use.

**Comment by Sinhk** [comment]
Is this included in 1.0.3? I'm still getting a signature error from Rider
> NuGet.Credentials.PluginException: The plugin at 'C:\Users\X\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe' did not have a valid embedded signature.

**Comment by JohnSchmeichel** [comment]
It will be in 1.0.4, releasing later today.

**Comment by JohnSchmeichel** [comment]
Release is published (but not latest yet), can you try it out?

```powershell
iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -Version 1.0.4 -Force"
```

**Comment by Sinhk** [comment]
Yes, Rider is happy now 👍 Thanks
