### ISSUE TITLE
Script default get .net 6 package

### ISSUE THREAD

**Issue by Maverick1983** [microsoft/artifacts-credprovider#396]
I have a lot of solution that use, on Dockerfile, this call:

_ENV AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION=v1.0.0
RUN wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash
ENV NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS 20
ENV NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS 20_

Now need to add this
`ENV USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER=false`

otherwise the script get .net 6 package.

It's possible get default this package 'Microsoft.NuGet.CredentialProvider.tar.gz' ?

**Comment by JohnSchmeichel** [comment]
This is by design, please see the announcement here: https://github.com/microsoft/artifacts-credprovider/discussions/386
