### ISSUE TITLE
Persist credentials independent of session cache

### ISSUE THREAD

**Issue by m-soltani** [microsoft/artifacts-credprovider#402]
I am on mac using pwsh core 7 and after when I try to register an azure artifact feed as a private powershell repository as described in the doc here: [register private feed](https://learn.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops#:~:text=Use%20an%20Azure%20Artifacts%20feed%20as%20a%20private,repository%20Open%20an%20elevated%20PowerShell%20prompt%20window.%20). This works perfectly for the first time I want to register the repository, but when I close the session and create a new session again, it asks me for a device authentication flow every time I want to run a command related to the registered repository. 

Is there a way to cache the credentials independent of the session?

**Comment by JohnSchmeichel** [comment]
I would expect the credential provider's token cache to be working here.. suspect that PS is passing -IsRetry in these cases. Can you enable MSAL and see if it helps here? There's token caches enabled by default for MSAL (and work much better).

Ensure this gets enabled for all sessions:
```
export NUGET_CREDENTIALPROVIDER_MSAL_ENABLED=true
```
