### ISSUE TITLE
dotnet restore --interactive

### ISSUE THREAD

**Issue by baskialdensys** [microsoft/artifacts-credprovider#427]
Unable to find package OpenAI.Api. No packages exist with this id in source(s): azure-sdk-for-net

**Comment by JohnSchmeichel** [comment]
Doesn't sound like a credential provider issue. What does your nuget.config look like here?

**Comment by baskialdensys** [comment]
When I tried 'dotnet restore --interactive', I never received any credential prompt. 

Nuget.config :

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="azure-sdk-for-net" value="https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json" />
  </packageSources>
</configuration>

**Comment by baskialdensys** [comment]
When I tried 'dotnet restore --interactive',  I never received any credential prompt. 

Nuget.config 
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="azure-sdk-for-net" value="https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json" />
  </packageSources>
</configuration>

**Comment by JohnSchmeichel** [comment]
Not seeing the nuget.config showing up... you probably are not seeing a credential prompt because this is not a credential issue. If you're unable to find a package nuget is informing you that from the available sources in your nuget.config that package was not found.

**Comment by baskialdensys** [comment]
add key="azure-sdk-for-net" value="https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json"

**Comment by JohnSchmeichel** [comment]
If you check the [feed](https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net) you'll see that there is no package OpenAI.Api and no upstream source to pull it from, hence the error nuget is reporting. You should follow up with the feed owners to get the package added.

**Comment by baskialdensys** [comment]
I'm simply using the dotnet sample provided by the Microsoft team without making any modifications. I had the impression that this private package was being maintained by the Azure SDK team.

**Comment by JohnSchmeichel** [comment]
You'll need to follow up with that team then to update the sample as it appears to have gone stale?
