### ISSUE TITLE
Support Azure managed identity authentication with AzureDevOps feeds

### ISSUE THREAD

**Issue by elbardel** [microsoft/artifacts-credprovider#437]
AzureDevOps released in public preview a feature to enable [authentication with Azure Active Directory service principals & managed identities](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops) and they are encouraging people to use it for automation instead of PATs.

It would be useful to have support for managed identities authentication in artifacts-credeprovider, in the same way it already supports AAD authentication with users.
The managed identity client id could be provided in an environment variable.

This would greatly simplify the set up for automation.

**Comment by elbardel** [comment]
This is still relevant.

**Comment by johnterickson** [comment]
Until this is wired up, it is possible to use the Azure CLI task to extract the AAD token and use it for Artifacts.  I only have a sample for Actions: https://github.com/johnterickson/actions-oidc-demo

**Comment by wanghenry-msft** [comment]
Written an [ado extension](https://github.com/wanghenry-msft/ado-auth-tools/blob/main/Tasks/NuGetAuthenticateNew/index.ts) that can be used to pull auth tokens from federated credentials. The only sticking problem is that this does not support passing a bearer auth token and soft-requires a plain PAT token (which is now being hard phased out)

**Comment by embetten** [comment]
release 1.2.0-alpha now natively supports MI / SP set up instructions can be found on the [PR description](https://github.com/microsoft/artifacts-credprovider/pull/492). Please let me know if you have and feedback or find any issues!

**Comment by StephenEdmondsPG** [comment]
I had a look at using this with our Team City hosted builds, but being locked to only using a certificate is a bit of a pain point. Team City can handle distributing the Service Principal secret securely (and this is the approach we take with other jobs that need to auth), but not distributing a certificate onto those build agents. Our preference would be for the plugin to support secret based authentication - then it's our choice as to how we want to authenticate

**Comment by wanghenry-msft** [comment]
I know that secrets _is_ explicitly (and intentionally disallowed) because of bad security practices, but it might be good to support WIF (which it currently does not do so)

**Comment by embetten** [comment]
> I had a look at using this with our Team City hosted builds, but being locked to only using a certificate is a bit of a pain point. Team City can handle distributing the Service Principal secret securely (and this is the approach we take with other jobs that need to auth), but not distributing a certificate onto those build agents. Our preference would be for the plugin to support secret based authentication - then it's our choice as to how we want to authenticate

Thank you for your feedback. While we understand this is additional configuration and set up, at this time, we are not considering adding secrets. However, if anyone is interested in secrets, please upvote the above comment. Depending on the demand, we can reconsider incorporating this work in the future.

**Comment by embetten** [comment]
> I know that secrets _is_ explicitly (and intentionally) disallowed because of bad security practices, but it might be good to support WIF (which it currently also does not do so either)

Please let us know what ADO Feed WIF scenarios you are interested in being supported.

**Comment by embetten** [comment]
Released support with  non pre-release version: https://github.com/microsoft/artifacts-credprovider/releases/tag/v1.2.1. Instructions [here ](https://github.com/microsoft/artifacts-credprovider/issues/437#issuecomment-2192569312)
