### ISSUE TITLE
Random failure to authenticate to Azure DevOps using dotnet tool

### ISSUE THREAD

**Issue by JoeGaggler** [microsoft/artifacts-credprovider#44]
The credential provider fails to properly authenticate with an Azure DevOps feed about 50% of the time as shown below:

![dotnet-tool-install-randomly-fails-post](https://user-images.githubusercontent.com/27233871/49186971-ac05ba80-f32b-11e8-9245-89edd701dc2d.JPG)

A Fiddler trace shows that the "Authorization" header contains invalid credentials for the times that it fails:

> GET https://REDACTED/_packaging/REDACTED/nuget/v3/flat2/REDACTED/index.json HTTP/1.1
> X-NuGet-Session-Id: REDACTED
> User-Agent: NuGet .NET Core MSBuild Task/4.9.0 (Microsoft Windows 10.0.17134 )
> X-NuGet-Client-Version: 4.9.0
> Accept-Language: en-US
> Accept-Encoding: gzip, deflate
> **Authorization: Basic Og==**
> Host: REDACTED

Decoding "Og==" in Base64 results in ":"

**Comment by satbai** [comment]
Hi @JoeGaggler have you tried the command with --interactive and does that succeed every time or does it also fail 50% of the time? Which version of the Artifacts Credential Provider are you using? Also, could you run this with --verbosity detailed so that we can get more logs?

**Comment by JoeGaggler** [comment]
Hi @satbai, the `dotnet tool` command does not seem to support the --interactive flag yet. I used the "Automatic PowerShell installation" instructions, so I believe I am on the latest version. Here is the log for one of the failures:

[credential-error.txt](https://github.com/Microsoft/artifacts-credprovider/files/2634400/credential-error.txt)

**Comment by satishkumaarponnusamy** [comment]
Can you run `dotnet restore --no-cache --interactive` and then run `dotnet tool`? If your nuget packages are already cached in local machine, it will not be pulled down, run `nuget locals all -clear` to clear the cache before restore. 

If restore fails, add `--verbosity diag` to restore command and share the logs.

**Comment by JoeGaggler** [comment]
`dotnet restore` fails with the following error:

> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

The private NuGet source is stored in the user profile config: `%APPDATA%\NuGet\NuGet.Config`

_News in the last couple days_: `dotnet tool` is adding the `--interactive` flag via [this PR](https://github.com/dotnet/cli/pull/10524).

**Comment by satishkumaarponnusamy** [comment]
You might be running from a folder that doesn't have either (solution) *.sln or (project) *.csproj file.

Yes, having package source in user scoped NuGet config should work.
That's great.

**Comment by alexmullans** [comment]
@JoeGaggler, with `dotnet tool --interactive` merged, were you able to this working?

**Comment by JoeGaggler** [comment]
@alexmullans - it looks like that commit has not been deployed in the latest SDK (2.2.103). I am not able to build the cli from source at the moment, so I cannot confirm that it is working yet.

**Comment by JoeGaggler** [comment]
The `--interactive` flag is working using the daily build of .NET Core 3.0, and I was able to successfully authenticate with the Azure DevOps feed.

**Comment by mvonballmo** [comment]
I'm getting the same error as OP. Is there any way to pull a tool from an authenticated Azure feed without using preview-release tools? I'm using 2.2.300. I'm launching my installation with the following command line (redacted names/URLs):

```
dotnet tool update *** -g --add-source https://****.pkgs.visualstudio.com/_packaging/***/nuget/v3/index.json
```

The `--interactive` flag doesn't exist in my tools version. From where is NuGet obtaining credentials? I see an `AppData/Local/.IdentityService/AccountStore.json` file with suspiciously familiar information (two accounts are listed there), but am not sure where else to look or where to set the authentication information.

Thanks in advance for any help.

**Comment by mvonballmo** [comment]
I've figured out how to set up an authenticated NuGet feed.

It's a bit obvious in hindsight, but I wasn't aware that you could add NuGet sources with credentials.

That solved my problem.

If it helps, I've written a [small post to help our developers set things up](https://encodo.com/latest/developer-blogs/how-to-use-authenticated-nuget-feeds/).

**Comment by shubham90** [comment]
Thanks @mvonballmo for the blogpost. Closing this issue as this is fixed with latest .net sdk version.
