### ISSUE TITLE
Running Crendential Provider Behind Proxy

### ISSUE THREAD

**Issue by rinobatin** [microsoft/artifacts-credprovider#441]
I'm running dotnet/nuget with credential provider behind company proxy (with Windows auth). I'm getting the following error when I try to restore

```
Failed to acquire session token: System.Net.Http.HttpRequestException: 
The proxy tunnel request to proxy 'http://webproxy.company.com:8080/' failed with status code '407'."
```

Is it okay to add proxy support? If so, how do you want this implemented? I'm happy to create a PR.

I can use dotnet restore/nuget and nuget.exe just fine with the proxy to another source e.g. to nuget.org

**Comment by JohnSchmeichel** [comment]
Using default credentials with proxies should work, might be a bug fix level change required if that's not working as expected (could be mistaken here though). Can you collect debug logs and provide them here? Curious which http call is getting that 407 result.
