### ISSUE TITLE
Docker sample does not work on Windows

### ISSUE THREAD

**Issue by JohnSchmeichel** [microsoft/artifacts-credprovider#448]
Starting a new issue as a follow up from https://github.com/microsoft/artifacts-credprovider/issues/446 where the Windows [docker sample](https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider) does not work. When following the sample the docker build may end up with the error `C:\app\dotnetapp.csproj : error NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/<org>/<project>/_packaging/<feed>/nuget/v3/index.json.`

For Windows Nano Server based images docker runs as `ContainerUser` by default, which is unable to install the credential provider as detailed in https://github.com/microsoft/artifacts-credprovider/issues/201. As a workaround the `ContainerAdministrator` user is used to install the credential provider, however doing so installs into the C:\\Users\\ContainerAdministrator\\.nuget directory, which is not visible when the build later runs as `ContainerUser`. Hence the NuGet failures trying to load the service index.

### Workarounds
Have few workarounds here until this can be fixed and the sample updated (note this issue only exists on Windows Nano Server containers as it runs as `ContainerUser` by default):

#### Option 1
Move the `USER ContainerUser` instruction after the `RUN dotnet ...` instructions. This runs the build as `ContainerAdministrator` which will be able to see and use the installed credential provider. This may or may not be desirable.

#### Option 2
Use the following docker instructions to grant the additional permissions required to run the credential provider script as `ContainerUser`. This also may not be desirable.

```docker
# Grant BUILTIN\Users access to read & delete from the TEMP directory
USER ContainerAdministrator
RUN & icacls C:\Windows\Temp\ /grant *S-1-5-32-545:'(OI)(CI)(RD,DE,DC)'
USER ContainerUser

# Install the cred provider
WORKDIR /Windows/Temp
RUN Invoke-WebRequest https://raw.githubusercontent.com/microsoft/artifacts-credprovider/master/helpers/installcredprovider.ps1 -OutFile installcredprovider.ps1; `
    .\installcredprovider.ps1; `
    del installcredprovider.ps1
```

**Comment by JohnSchmeichel** [comment]
As for a fix here, ideally the credential provider can be installed as `ContainerUser` without elevating, but there are a few unfortunate limitations here:
1. The install script uses the TEMP env var (and .NET methods based off that) to create temporary files, but `ContainerUser` doesn't have any access to delete the temp files it creates (hence the icacls workaround to resolve this, granting read/delete permissions).
2. On Nano Server there just isn't a good scratch location for temp files, so creating and cleaning up temp files needs to be done in the docker build itself.

The core problem imho is that these script-based install mechanisms leave a lot to be desired and run into these platform limitations both on capability and differences. Using a mechanism like the proposed https://github.com/NuGet/Home/issues/12567 would make all of these problems obsolete and allow the credential provider install to work cross-platform.

In the near term however, I'd propose the following changes to keep the spirit of the `ContainerUser` permission model (and the docker sample's goal of building within the container as a low-privileged account in a 2-phase build for isolation):
1. Update the installcredprovider.ps1 script to allow an install path to be specified, falling back to TEMP if none is specified.
2. Update the docker sample to install into a custom temp folder, such that it has full permissions to clean up after install.

**Comment by JohnSchmeichel** [comment]
Able to do this in the sample itself with https://github.com/dotnet/dotnet-docker/pull/4828

**Comment by embetten** [comment]
not stale.

**Comment by JohnSchmeichel** [comment]
maybe stale?

**Comment by damien-c-d** [comment]
I'm having this problem with Azure DevOps pipeline accessing the artifacts NuGet Feed. Any ideas? It was working last week and now its not. No changes have been made to the pipeline.

```
##[warning]C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(169,5): Warning :     [CredentialProvider]Unknown Status: Unexpected
Error: 0xffffffff80070520
Context: Winrt exception was thrown during GetTokenSilently '(pii)'.
Tag: 0x2339e502 (error code -2147023584) (internal error code 590996738)
```

The error messages its giving aren't helpful at all.
