### ISSUE TITLE
README: Linux one-line Credential Provider installer script does not work

### ISSUE THREAD

**Issue by matteopessina** [microsoft/artifacts-credprovider#450]
Hi, 
in README.md the command `sh -c "$(curl -fsSL https://aka.ms/install-artifacts-credprovider.sh)"` throw errors because the script downloaded used features specifc of `bash` such as `[[ expr ]]` and not provided by `sh`.
I suggest to change it to 
`bash -c "$(curl -fsSL https://aka.ms/install-artifacts-credprovider.sh`

**Comment by amp-powell** [comment]
Fixed with this PR: https://github.com/microsoft/artifacts-credprovider/pull/457
