### ISSUE TITLE
Use Windows authentication context from in WSL

### ISSUE THREAD

**Issue by nicholass-alcidion** [microsoft/artifacts-credprovider#461]
When working in WSL it is possible to get other credential providers (such as [git](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup)) to use the authentication context from Windows inside of WLS

It would be extreamly helpful if this provider could also be configured to do so

**Comment by johnterickson** [comment]
Not official MSFT, but I made this during a hackathon: https://github.com/johnterickson/CredentialProvider.Redirect

**Comment by nicholass-alcidion** [comment]
Not stale.

**Comment by nicholass-alcidion** [comment]
This remains a problem

**Comment by p10tyr** [comment]
Got to be carefull with the use windows context.. as some people are logged into on AD but may authenticate against other AD's.. its a real pain in Windows, especially with Cake build. 

It just needs to popup --- or in WSL show you the QR code to select what you want to authenticate against..  although the new WSL now support X proxy? so it could work?
