### ISSUE TITLE
The proxy tunnel request to proxy failed with status code '407'

### ISSUE THREAD

**Issue by solarding** [microsoft/artifacts-credprovider#495]
Using a very restricted Laptop, behind Proxy (no way to change the winhttp proxy )
I got this error, there is no way for interactive authenticate

PS C:\Users\abc\source\xRM_API\xRM> dotnet nuget push --skip-duplicate --interactive --source [https://pkgs.dev.azure.com/xxxx/_packaging/xRM/nuget/v3/index.json](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkgs.dev.azure.com%2Fxxxx%2F_packaging%2FxRM%2Fnuget%2Fv3%2Findex.json&data=05%7C02%7Cjianyang.ding%40soprasteria.com%7Cdc3688ccc37c45c708ef08dc784657dd%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C638517490724488610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=eryeytD0qdxnpHbruJd0yUEquK08r0lQ8i6Hga3D7mg%3D&reserved=0) --api-key AZ xxxx.nupkg

error:     [CredentialProvider]Failed to acquire session token: System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://web-proxy.snb.zz:8080/' failed with status code '407'."

error:    at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)

error:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

error:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

error:    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)

error:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)

error:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

error:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

error:    at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)

error:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

error:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

error:    at NuGetCredentialProvider.CredentialProviders.Vsts.AuthUtil.GetResponseHeadersAsync(Uri uri, CancellationToken cancellationToken) in D:\a\_work\1\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\IAuthUtil.cs:line 147

error:    at NuGetCredentialProvider.CredentialProviders.Vsts.AuthUtil.GetAadAuthorityUriAsync(Uri uri, CancellationToken cancellationToken) in D:\a\_work\1\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\IAuthUtil.cs:line 55

error:    at NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider.HandleRequestAsync(GetAuthenticationCredentialsRequest request, CancellationToken cancellationToken) in D:\a\_work\1\s\CredentialProvider.Microsoft\CredentialProviders\Vsts\VstsCredentialProvider.cs:line 99

error:    at NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.HandleRequestAsync(GetAuthenticationCredentialsRequest request) in D:\a\_work\1\s\CredentialProvider.Microsoft\RequestHandlers\GetAuthenticationCredentialsRequestHandler.cs:line 82

error: Der Dienstindex für die Quelle [https://pkgs.dev.azure.com/xxxxx/_packaging/xRM/nuget/v3/index.json](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkgs.dev.azure.com%2Fstromnetzberlin%2F9751379e-4efc-4f7c-938c-16199e6dcf11%2F_packaging%2FxRM%2Fnuget%2Fv3%2Findex.json&data=05%7C02%7Cjianyang.ding%40soprasteria.com%7Cdc3688ccc37c45c708ef08dc784657dd%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C638517490724500108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YzHiHxZl4UaJ%2Fts24BMls3t08u1%2FLseVEmqLUi4GkiQ%3D&reserved=0) konnte nicht geladen werden.

error:   Response status code does not indicate success: 401 (Unauthorized).

**Comment by embetten** [comment]
The http client should be sending the default credentials on the above logged call - does the proxy require alternate credentials than default?
