### ISSUE TITLE
Breaking change in VSS_NUGET_EXTERNAL_FEED_ENDPOINTS

### ISSUE THREAD

**Issue by mrtristan** [microsoft/artifacts-credprovider#508]
As of yesterday we started receiving `The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for NuGet` across all of our build pipelines. We've been blaming and troubleshooting tokens that just happened to expire in the last 24 hours.

I just finally narrowed the issue down to yesterday's release (1.2.1).

Previously working code:
```
# worked prior to yesterday
RUN wget -qO- https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh | bash

WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./

ENV NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS {\"endpointCredentials\": [{\"endpoint\":\"${FEED_URL_NET}\", \"username\":\"${PAT_NET}\", \"password\":\"\"}]}

RUN dotnet restore -s $FEED_URL_NET
```

I confirmed that adding the following before the install had it working again
`ENV AZURE_ARTIFACTS_CREDENTIAL_PROVIDER_VERSION v1.1.1`

I narrowed down the fix to moving the PAT to the password instead of the username. Perhaps that's how it always should have been (as is documented) but FYI in case this was not an expected breaking change. Nothing in the release notes jumps out at me on this topic.

**Comment by embetten** [comment]
There was some refactoring to the parsing of the endpoint env variables as part of the 1.2.0-alpha release that was part of the 1.2.1 payload. 

We can make this clearer in the future, by ensuring relevant pre-release notes are also included in next latest release. But PATs in the username is not an expected scenario

**Comment by embetten** [comment]
closing.
