### ISSUE TITLE
Commit 2a289 breaks convenience scripts

### ISSUE THREAD

**Issue by Rhernandez513** [microsoft/artifacts-credprovider#525]
I noticed in CI the install script for artifacts-credprovider stopped working just now

![Image](https://github.com/user-attachments/assets/0dbf1ffa-b548-439a-b6a2-fdc84dc1de38)

![Image](https://github.com/user-attachments/assets/d850a21d-d732-449c-bd24-51dea016f16d)

https://github.com/microsoft/artifacts-credprovider/commit/2a2891c55c7fb01f39aba11c23bd083402ea7273#diff-a3d32842c27ade73028cfca0c3b9686dd84d09453a06b78d38829b88e9cac7d0

**Comment by cobya** [comment]
#526 should resolve this.

**Comment by Rhernandez513** [comment]
Verified works in CLI and CI, thanks @cobya
