### ISSUE TITLE
How to set VSS_NUGET_EXTERNAL_FEED_ENDPOINTS correctly

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/artifacts-credprovider#53]
I'm trying to set `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` environment variable but it looks like no effect.

Here are the steps to reproduce my problem.

Machine A:

1. Install `NuGet.exe` and `CredentialProvider.VSS.exe`

    ```sh
    choco install nuget.commandline nuget-credentialprovider-vss -y
    ```

2. Create new `nuget.config` file

    ```sh
    dotnet new nuget
    ```

3. Add my Azure Artifacts NuGet feed

    ```sh
    nuget sources add -Name {YourOrg} -Source https://{YourOrg}.pkgs.visualstudio.com/_packaging/{YourProject}/nuget/v3/index.json
    ```

4. Try pass the authenticate

    ```sh
    nuget list
    ```

5. Generate PAT by the following command.  Copy the "**Password**" property's value as PAT.

    ```sh
    CredentialProvider.VSS.exe -U https://{YourOrg}.pkgs.visualstudio.com/_packaging/{YourProject}/nuget/v3/index.json
    ```

Machine B:

1. Install `NuGet.exe` and `CredentialProvider.VSS.exe`

    ```sh
    choco install nuget.commandline nuget-credentialprovider-vss -y
    ```

2. Create new `nuget.config` file

    ```sh
    dotnet new nuget
    ```

3. Add my Azure Artifacts NuGet feed

    ```sh
    nuget sources add -Name {YourOrg} -Source https://{YourOrg}.pkgs.visualstudio.com/_packaging/{YourProject}/nuget/v3/index.json
    ```

4. Setup `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` environment variable.  The **[PAT]** is what I generated at Machine A.

    ```sh
    set VSS_NUGET_EXTERNAL_FEED_ENDPOINTS={"endpointCredentials": [{"endpoint":"https://{YourOrg}.pkgs.visualstudio.com/_packaging/{YourProject}/nuget/v3/index.json", "username":"VssSessionToken", "password":"[PAT]"}]}
    ```

5. Try pass the authenticate but this doesn't read `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` environment variable!

    ```sh
    nuget list
    ```

**I expected the pass authentication because I already set correct `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` environment variable!** Am I do something wrong?

**Comment by doggy8088** [comment]
I was misunderstanding the "PAT" means.  This is wrong steps.

**Comment by satbai** [comment]
Please also note that CredentialProvider.VSS.exe is a different cred provider. To use this one you can use [one of these scripts](https://github.com/Microsoft/artifacts-credprovider/tree/master/helpers) to install it to the correct location on your machine. Then you should be able to use the VSS_NUGET_EXTERNAL_FEED_ENDPOINTS environment variable. You can create a PAT in your Azure DevOps account https://dev.azure.com/<yourorg>/_usersSettings/tokens

**Comment by doggy8088** [comment]
I wrote a very detailed tutorial about this: https://blog.miniasp.com/post/2019/01/16/Setup-Azure-Artifacts-NuGet-Feeds.aspx

**Comment by csurfleet** [comment]
@doggy8088 Any chance of a version in English? I've tried translation tools but not getting anything useful.

I've tried all this in many permutations over weeks now and I still get errors CURLing from the container to the feed - "The user '' is not authorized to view this resource"

**Comment by doggy8088** [comment]
@csurfleet Please open PowerShell and run the following command:

```ps1
$env:VSS_NUGET_EXTERNAL_FEED_ENDPOINTS = '{"endpointCredentials": [{"endpoint":"https://{YourOrg}.pkgs.visualstudio.com/_packaging/{YourProject}/nuget/v3/index.json", "password":"[PAT]"}]}'
dotnet restore
```

Then you can pass the authentication.

**Comment by rhumborl** [comment]
For anyone checking this issue and wanting to translate https://blog.miniasp.com/post/2019/01/16/Setup-Azure-Artifacts-NuGet-Feeds.aspx, I did it in Chrome, but needed to manually set the source language to "Chinese (simplified)" as it was not automatically detected
