### ISSUE TITLE
dotnet restore --interactive - Conditional access device OS

### ISSUE THREAD

**Issue by JonathanSiemering** [microsoft/artifacts-credprovider#535]
```sh
dotnet restore --interactive
```

When i try to run this, the device login page of Microsoft shows the error, that i have no access from this machine. We use Conditional Access. It seems that the command not provide the os type in the device code authentication request. I tried this on MacOS.
On Windows it seems to work because of the Windows credential integration.

Can the device code authentication request provide device operating system?

**Comment by embetten** [comment]
I do not see a way to configure the MSAL public client nor device code flow with the os parameter, and it doesnt look like an accepted extraQueryParameter. Some sources
https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.publicclientapplicationbuilder?view=msal-dotnet-latest
https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-device-code

**Comment by embetten** [comment]
Even if you could, is there any guarantee the device code login was from the same machine? In theory couldn't you use a completely different machine to access the device code browser URL and add the code from the machine running the cred provider?

I think the conditional access policy is innately incompatible with device code flow, and if there is no other supported authentication method on the machine, then this cred provider would be unable to provide a valid token.
