### ISSUE TITLE
Self-hosted build agent and dotnet restore

### ISSUE THREAD

**Issue by danielwertheim** [Microsoft/artifacts-credprovider#60]
How are we supposed to configure this if a self-hosted agent is installed on a own server and a build script calls dotnet restore? I have a custom nuget.config that clears and adds:

1 - a Azure DevOps Artifacts feed
2 - NuGet org

Is it supposed to work if I:

Add environment variable: `NUGET_PLUGIN_PATHS` pointing to folder with the ZIPs plugins

Add environment variable: `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` with JSON

```
{"endpointCredentials": [{"endpoint":"https://myfeed.com/index.json", "username":"not-required", "password":"accesstoken"}]}
```

The access token has full rights to Packages feeds.

**Comment by zjrunner** [comment]
Is your self-hosted agent an Azure Devops Pipelines agent?  I'm trying to understand if you're running in Pipelines, but just using a manual script to restore instead of the existing pipeline tasks, or if you're trying to run in a separate CI/CD ecosystem entirely.

**Comment by satbai** [comment]
If you're using the NUGET_PLUGIN_PATHS variable, please make sure that it points to the .exe with NuGet or .dll with dotnet instead of the folder. For example, `NUGET_PLUGIN_PATHS="C:\path-to-cred-provider\CredentialProvider.Microsoft.dll"`. Also, instead of using the environment variable, you can use the [script](https://github.com/Microsoft/artifacts-credprovider/blob/master/helpers) to install the cred provider to the location that NuGet and dotnet knows to look for the plugin.

However, please let us know if you're using the pipeline tasks mentioned above - in that case I'll have to look into the task you're using.

**Comment by danielwertheim** [comment]
@zjrunner  Using Azure DevOps: 
- Repo
- Pipeline
- Artifacts feed

Using a devops pipeline agent. Everything works, except authentication against the Azure DevOps artifacts feed when it comes to restoring via `dotnet build` in the build script (CakeBuild in via Powershell task).

**Comment by satbai** [comment]
We recommend doing dotnet restore as a separate step before you do dotnet build to make it easier to trouble shoot. If dotnet restore still fails after changing the NUGET_PLUGIN_PATHS variable to point to the .dll and verifying you're using dotnet version 2.1.400 or greater, please run it with detailed verbosity and share the logs so we can investigate further.

**Comment by danielwertheim** [comment]
@satbai it works now, but I'm not sure if it can be to due the fact that something is cached from me getting it to work with a plain `dotnet restore` task (as in not in the build script)

I did clear the generated temp-nuget.config files etc and tried with my script after adjusting the `NUGET_PLUGINS_PATH` to point to the `dll` and then it worked.

**Comment by satbai** [comment]
Great! To rule out cache, you can check your [session token cache location](https://github.com/Microsoft/artifacts-credprovider#session-token-cache-locations), remove the possible existing cache and try again.

**Comment by danielwertheim** [comment]
@satbai unfortunately I was wrong... Tried running with diagnostics and debug (just `dotnet restore`) and still get:

"Unable to load the service index for source https://......"

"Response status code does not indicate success: 401 (Unauthorized)"

Running the build script it on the server manually works fine, and I have never provided any credentials there (via interactive or similar)

**Comment by danielwertheim** [comment]
@satbai I'm a bit embarrassed as I forgot to restart. Made a PR https://github.com/Microsoft/artifacts-credprovider/pull/61
