### ISSUE TITLE
Interactive UI question

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/artifacts-credprovider#68]
I'm looking to migrate from Microsoft.VisualStudio.Services.NuGet.CredentialProvider, but I'm a bit unclear as to what UI I should get when running in interactive mode.

Should I see a pop-up dialog (like I would get with the old provider), or is it just a console-based prompt? 

Or does it vary depending on whether I run `dotnet restore` or `nuget restore`?

**Comment by satbai** [comment]
It depends. With Windows using nuget.exe or msbuild in most cases you'll get a popup dialog. And with dotnet you'll get a device flow prompt in the console that will direct you to authenticate through a browser. Also, we'll in most cases try to do a non-interactive auth first and if that isn't successful we'll fall back to the popup dialog and then the device flow.

**Comment by flcdrg** [comment]
I think that makes sense. The code I'm updating is using .NET Core, whereas the code that I'd used the old credential provider was using .NET Framework/NuGet.exe - so I was surprised at first not to get a similar dialog popup.

Maybe adding some examples to the README or documentation (if this ends up on docs) would be useful to set expectations.
