### ISSUE TITLE
Example of working with dotnet:2.2-sdk-alpine

### ISSUE THREAD

**Issue by kieronlanning** [Microsoft/artifacts-credprovider#71]
I've been wrestling to get this working with the Alpine builds of the donet core SDK.

Is there an example of this anywhere?

**Comment by shubham90** [comment]
@kieronlanning I am trying to add this to alpine dotnet docker images. Similar code should work on alpine boxes as well. You can check that here: https://github.com/shubham90/dotnet-docker/blob/3edfe02ca476abdd653193c4344bf08832b6699a/2.2/sdk/alpine3.8/amd64/Dockerfile#L25

**Comment by kieronlanning** [comment]
@shubham90 Splendid, thanks! I'll try it tomorrow morning.

Is there a specific image I should pull from?

**Comment by shubham90** [comment]
Right now this hasn't been merged yet. But any dotnet 2.* sdk image should work.

**Comment by kieronlanning** [comment]
@shubham90 I may have missed something here, what do I do here? Copy that whole file as a replacement for my normal base image?

**Comment by shubham90** [comment]
@kieronlanning You can copy just the download, untar the credential provider and set the env var steps from that file if you want the credential provider in your container. 
Another [example gist ](https://gist.github.com/shubham90/ad85f2546a72caa20d57bce03ec3890f) on how you can do it in your base image.

**Comment by kieronlanning** [comment]
Gotch, thanks!
