### ISSUE TITLE
In box cred provider is very old

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/artifacts-credprovider#72]
The version of the cred provider that is in current Visual Studio 2019 previews is 0.1.5 from September 2018.  There have been a lot of improvements around Windows auth since then but I'm having to tell people to manually install the latest version.  Will you be updating the version that ships with Visual Studio soon?

**Comment by satbai** [comment]
Perfect timing for this question! The newest preview, 16.0.0 Preview 4.0, of Visual Studio 2019 includes the version 0.1.11 of this cred provider.

**Comment by jeffkl** [comment]
Great, thanks. Are there plans to service 2017?  I have some team members who won’t install previews :(

**Comment by satbai** [comment]
It looks like it's going to be another month before [VS 2019](https://visualstudio.microsoft.com/vs2019-launch/) is generally available. As of now there's no plans to update previous versions of VS, is there @zjrunner @alexmullans?

**Comment by alexmullans** [comment]
Are there any more feature releases of 2017 planned? @anangaur do you know? If not, I don't think we'd do a special release just for this.

**Comment by anangaur** [comment]
> Are there any more feature releases of 2017 planned? 

There should be. @rrelyea would know better.

**Comment by zjrunner** [comment]
We followed up today for a different 2017-ship question and it sounds like no planned major releases and any others would be high-bar hotfixes.

**Comment by alexmullans** [comment]
@zjrunner great, thanks. In that case, @jeffkl, I'm going to close this since the work to get 2019 updated with a recent version is done and awaiting release.
