### ISSUE TITLE
installcredprovider.ps1 -force doesn't actually overwrite previous contents

### ISSUE THREAD

**Issue by bergbria** [Microsoft/artifacts-credprovider#79]
== Repro ==
1. Have an older version of the cred provider installed (e.g. 0.1.11.0)
2. Run installCredProvider.ps1 -AddNetFx -Force
3. Check the installed version (e.g. via `(get-item -Path "$Env:userprofile\.nuget\plugins\netfx\CredentialProvider.Microsoft\CredentialProvi
der.Microsoft.exe").VersionInfo | Format-List -Force`

The version will still be the old version instead of whatever the current version is (currently 0.1.15.0)

**Comment by bergbria** [comment]
The problem seems to be that this line doesn't actually replace the contents of a directory if it already exists.
`Copy-Item <source> -Destination <dest> -Force -Recurse`
This does, but doesn't create the destination dir if it's not already there.
`Copy-Item <source>\* -Destination <dest> -Force -Recurse`

I'm not a PowerShell guru, but possibly the best fix is to just Remove-Item the destination directory before copying to it.

**Comment by satbai** [comment]
Thanks for filing!
