### ISSUE TITLE
installcredprovider scripts should allow to pass in a version

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/artifacts-credprovider#88]
Passing in a version explictly instead of relying on latest is important for deterministic builds.

**Comment by satbai** [comment]
Reopening the issue since my PR only added the enhancement to the .ps1 script, but not the .sh script.

**Comment by satbai** [comment]
Had to revert the PR, here's the new one: https://github.com/microsoft/artifacts-credprovider/issues/88
