### ISSUE TITLE
installcredprovider script should respect NUGET_PACKAGES env variable

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/artifacts-credprovider#89]
See https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

**Comment by satbai** [comment]
Hi @ViktorHofer, I just checked the NUGET_PACKAGES variable and tried it out. It looks like for NuGet to find the auth plugin, the cred provider still needs to live in %userprofile%/.nuget/plugins even if I use the  the NUGET_PACKAGES variable and the packages folder isn't %userprofile%/.nuget/packages anymore. There is a chance that I misunderstood the ask, however. Please feel free to re-open the issue if I misunderstood, and explain in detail what the request for the NUGET_PACKAGES env var is. Thanks!

**Comment by ViktorHofer** [comment]
The script currently hardcodes the path to the packages folder and does not honor the NUGET_PACKAGES environment variable: https://github.com/microsoft/artifacts-credprovider/blob/master/helpers/installcredprovider.ps1#L23

**Comment by satbai** [comment]
That is the location of the plugin, not the packages folder. Was the install script failing for you? If it was, maybe the .nuget folder didn't exist? If that's the case I can modify the script to check for the folder.

**Comment by ViktorHofer** [comment]
Right, why does the plugin need to be installed at that location? Why does nuget not try to resolve the same way as it determines the packages folder location?

**Comment by satbai** [comment]
Here's the [spec ](https://github.com/NuGet/Home/wiki/NuGet-Cross-Plat-Credential-Plugin#plugin-installation-and-discovery)on how NuGet finds the cred provider plugin. Basically, %userprofile%/.nuget/plugins is a location NuGet has chosen to look from when trying to authenticate to a package source endpoint. That's why the script always installs the plugin to the same location.

**Comment by ViktorHofer** [comment]
Can we change that / is there a reason for that?

**Comment by satbai** [comment]
I don't think the location can currently be changed by users. Although, if you need to have the cred provider in a different location, you can manually move it to a location you prefer and then use the NUGET_PLUGIN_PATHS environment variable described in the spec to point to the cred provider .exe or .dll file.

**Comment by satbai** [comment]
What we could do is add a comment to the script or update the readme and explain that if the cred provider needs to be in a different location for some reason, you can use the NUGET_PLUGIN_PATHS variable. Would that have been helpful?

**Comment by ViktorHofer** [comment]
It doesn't look like `NUGET_PLUGIN_PATHS` env var is respected in the script? Was looking at the sh script.

**Comment by satbai** [comment]
That's correct. The NUGET_PLUGIN_PATHS env var needs to be set up manually. The script only installs the cred provider to the pre-determined location NuGet looks for.
