### ISSUE TITLE
Change the Azure Artifacts download to this

### ISSUE THREAD

**Issue by slang25** [microsoft/artifacts-credprovider#90]
Currently when you go to Azure Artifacts and click `Connect to feed`, you see this:

![image](https://user-images.githubusercontent.com/1341446/55732011-18e43c00-5a13-11e9-8bc7-fe4e7d7777ea.png)

Given that Gen 1 credential providers are soon to be deprecated, shouldn't the bits in this repo be what is linked to from there?

Edit: apologies if this is the wrong place to raise it

**Comment by elbatk** [comment]
hi @slang25 , thanks for the feedback. We're taking a look the entire "connect to feed" experience, but we've also talked about updating outdated versions and such in it before we make large updates. Hoping we can get it updated beforehand since we've gotten a few suggestions now.

**Comment by satbai** [comment]
Thanks for raising the issue! The instructions in the Connect to feed dialog now recommend using this cred provider instead.
