### ISSUE TITLE
Unable to use credential provider in a multistage docker build using a dotnet core 3.0 image

### ISSUE THREAD

**Issue by markphillips100** [microsoft/artifacts-credprovider#92]
I start my multistage docker builds with `FROM mcr.microsoft.com/dotnet/core/sdk:3.0` as I'm evaluating **.NET Core 3.0.0-preview5**.  The code I build has dependencies in a private NuGet feed so I use the following along with `ARG VSS_NUGET_EXTERNAL_FEED_ENDPOINTS`  to supply the required auth info:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0
ARG VSS_NUGET_EXTERNAL_FEED_ENDPOINTS

# support private nuget feeds using the env VSS_NUGET_EXTERNAL_FEED_ENDPOINTS
RUN wget https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh \
   && chmod +x installcredprovider.sh \
   && ./installcredprovider.sh
``` 

Feed authorization has worked in the past when the base image is a sdk:2.2 or similar tag.  The problem with using the sdk:3.0 tag is that the credentials provider is dependent on .NET Core 2.1 which is unavailable in the base docker image.

Is there a version of the credential provider built for .NET Core 3.0.0 previews, preferably the latest?

**Comment by zarenner** [comment]
Hi @markphillips100,

There is not currently a version of the credential provider built for .NET Core 3.0 preview. While not on our immediate backlog, we are currently investigation different possible ways of distributing the credential provider (besides the current install script), and runtime support will certainly be a decision factor.

Is there anything blocking you from building and running your own .NET Core 3.0 version of the credential provider? If not, I'm happy to help with doing so if you are having issues.

**Comment by zarenner** [comment]
Dup of #51 @shubham90 fyi

**Comment by markphillips100** [comment]
Sorry for my late response @zarenner .  I'll look into building my own core 3 preview version for now.  If I get into issues I'll be in touch.

**Comment by markphillips100** [comment]
@zarenner my attempts at creating a .net core 3-preview5 version have stumbled a little so wonder if you can help?

The solution builds fine in VS2019 16.1.0.  All tests pass.

I'm getting an error from an Azure DevSpaces `.vsts-ci.yaml` build (PushNupkg:false) which occurs during the `Build CredentialProvider` task.  Here's a snippet of the log:
```
/opt/hostedtoolcache/dncs/3.0.100-preview5-011568/x64/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(145,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/home/vsts/work/1/s/CredentialProvider.Microsoft/CredentialProvider.Microsoft.csproj]
/opt/hostedtoolcache/dncs/3.0.100-preview5-011568/x64/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(145,5): error MSB4018: System.TypeLoadException: Could not load type of field 'Microsoft.NET.Build.Tasks.DependencyContextBuilder2:_filteredPackages' (12) due to: Could not resolve type with token 01000020 from typeref (expected class 'NuGet.Packaging.Core.PackageIdentity' in assembly 'NuGet.Packaging, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35') assembly:NuGet.Packaging, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:NuGet.Packaging.Core.PackageIdentity member:(null) [/home/vsts/work/1/s/CredentialProvider.Microsoft/CredentialProvider.Microsoft.csproj]
```

**Setup and changes**
I forked the repo and branched [here](https://github.com/markphillips100/artifacts-credprovider/tree/core3-preview5).  If you compare you'll see the changes I've made but in summary I did the following:

1. SDK installer version changed to `3.0.100-preview5-011568`
2. Target `netcoreapp3.0` in csproj file, and changed all occurrences of `netcoreapp2.1` to `netcoreapp3.0`.

The error occurred with just those changes so I also did the following but the error occurs still:

3. Updated NuGet.Protocol reference to 5.1 - not sure this is necessary or not
4. Install NuGet 5.1 - again, not sure this is necessary or not.

**Comment by zarenner** [comment]
Looks like you're hitting this issue (all same issue, just different info about it):
* https://github.com/NuGet/Home/issues/7956
* https://developercommunity.visualstudio.com/content/problem/481018/resolvepackageassets-task-failed.html
* https://rider-support.jetbrains.com/hc/en-us/articles/360004180039-Incompatible-versions-of-Mono-MSBuild-and-NET-Core-SDK-MSB4018-

I've confirmed that building using dotnet (instead of the MSBuild task) succeeds:
https://dev.azure.com/zlrenner/ArtifactsCredProviderUnofficial/_build/results?buildId=410&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

Let me know if you have trouble with the same.

**Comment by markphillips100** [comment]
Thanks @zarenner, builds fine now after switching to dotnet cli.  I should be good from here.
