### ISSUE TITLE
Nuget.exe prompting for credentials on every restore

### ISSUE THREAD

**Issue by AMoghrabi** [microsoft/artifacts-credprovider#94]
Hello,

I have the credential provider installed at `%userprofile%/.nuget/plugins`. It works fine for the `dotnet` CLI. I have used the `--interactive` switch once and it has saved my credentials and reuses the cached creds on subsequent `dotnet` operations.

I'm now trying to have `nuget.exe` cache my credentials. However, on each `nuget restore` run, it prompts me for my credentials when trying to authenticate against Azure Artifacts.

Tool versions:
```
MSBuild: 15.9.21.664
nuget.exe: 4.9.4.5839
```

I noticed when running `nuget restore`, the tool outputs this:

```
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
```

Is it likely I need to use interactive mode with `msbuild` first before I can use `nuget.exe` without providing credentials? 

I'm running `msbuild /t:restore /p:nugetInteractive=true` but it doesn't seem to be restoring any of my packages. I'll keep trying and in the meantime, I'm hoping to hear back from one of the contributors here.

Thanks for your help and thanks for developing this great tool :)

**Comment by zarenner** [comment]
Hi @AMoghrabi,

When you installed the credential provider, did you use the -AddNetfx option (or manually copy the netfx folder)? nuget.exe uses the .NET Framework version of the credential provider in `%userprofile%/.nuget/plugins/netfx`, as opposed to the one in `%userprofile%/.nuget/plugins/netcore`.

You should be able to run "nuget.exe restore ..." (as long as you don't pass -NonInteractive), running msbuild first is not required.

**Comment by AMoghrabi** [comment]
Hello @zarenner,

Thanks for the reply. I did not copy the `netfx` folder because I thought it wasn't required. I misunderstood this piece of the documentation found in the `README`:

>Note: copying the netfx directory is not recommended unless you don't plan to install an edition of Visual Studio (including the Build Tools edition). All Visual Studio editions come with (and automatically update) the netfx version of the Credential Provider.

My apologies, and thanks for clarifying 👍 I'll give this a shot and close the issue if it works out.

**Comment by AMoghrabi** [comment]
Your solution workers, thanks again. Would you mind clarifying the text I quoted above? I'm still a little confused about what it's trying to communicate.

**Comment by zarenner** [comment]
That documentation confuses me as well, to be honest. I believe it may be incorrect - while VS does come with the credential provider (since the Package Manager in VS uses it), it's not in a path that the nuget.exe plugin discovery mechanism will find.

Let me confirm this, and if that's indeed the case we'll get that documentation updated. Sorry for the confusion.

**Comment by AMoghrabi** [comment]
Not a problem! I appreciate the quick responses.

**Comment by zarenner** [comment]
Discussing changes to docs in #95

**Comment by zarenner** [comment]
Updated docs, closing this issue. Thanks for reporting, I'm sure it'll help others confused by the documentation as well. Please let me know if anything is still confusing.
